### ISSUE TITLE
Thank you for library

### ISSUE THREAD

**Issue by coppercele** [h2zero/NimBLE-Arduino#102]
I don't know where send message to project, I wrote here.
if its not good, pls delete.

I connected BLE HID device with ESP32(M5StickC) by using this library.
I cannot connect with NimBLE included ESP-IDF.

I wrote an aticle(In Japanese)

NimBLEでESP32(M5StickC)にBLE HIDデバイスを接続する - Qiita
https://qiita.com/coppercele/items/4ce0e8858a92410c81e3

Thank you!

**Comment by h2zero** [comment]
@coppercele You're welcome, nice to see it's working for you! Nice article as well!
