### ISSUE TITLE
PSRAM for BLE stack

### ISSUE THREAD

**Issue by darshan-mirajkar** [h2zero/NimBLE-Arduino#105]
Can we use PSRAM for BLE stack?? If yes what are the changes required?

**Comment by h2zero** [comment]
I think this is possible, I have not tested. 

You would need to change [this line](https://github.com/h2zero/NimBLE-Arduino/blob/05c68ed8926d1144191ce469001b6a3f3d13f715/src/nimconfig.h#L122) in nimconfig.h to `CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL`.

Let me know if that works.

**Comment by darshan-mirajkar** [comment]
Sure... I am looking for module with PSRAM...I'll let you know

**Comment by ntwallace** [comment]
@h2zero changing that line results in:

```lib/NimBLE/src/port/src/esp_nimble_mem.c: In function 'nimble_platform_mem_malloc':
lib/NimBLE/src/port/src/esp_nimble_mem.c:31:47: error: #elif with no expression
lib/NimBLE/src/port/src/esp_nimble_mem.c: In function 'nimble_platform_mem_calloc':
lib/NimBLE/src/port/src/esp_nimble_mem.c:44:47: error: #elif with no expression
*** [.pio/build/esp-wrover-kit/lib839/NimBLE/port/src/esp_nimble_mem.c.o] Error 1
```

It looks like in `esp_nimble_mem.c` all the `#elif`s are missing a `defined`. Adding that fixes the problem and the stack loads in PSRAM, e.g.:
```
#ifdef CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL
    return heap_caps_malloc(size, MALLOC_CAP_INTERNAL|MALLOC_CAP_8BIT);
#elif defined CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL
    return heap_caps_malloc(size, MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);
#elif defined CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_IRAM_8BIT
    return heap_caps_malloc_prefer(size, 2, MALLOC_CAP_INTERNAL|MALLOC_CAP_IRAM_8BIT, MALLOC_CAP_INTERNAL|MALLOC_CAP_8BIT);
```

**Comment by h2zero** [comment]
@ntwallace Thanks for reporting this. Please consider raising the issue in esp-idf as that file is tracked from there. In the meantime I will consider fixing it here for this library's purposes.

**Comment by h2zero** [comment]
After looking at this again I think the fix is actually to define a value of 1 to the config define, such as:

`#define CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL 1`

I will add this line, commented, in nimconfig.

**Comment by ntwallace** [comment]
Ah good catch, makes sense. Thanks.

**Comment by darshan-mirajkar** [comment]
Nice one guys... I am also looking for hardware with PSRAM to test this.

**Comment by ntwallace** [comment]
@darshan-mirajkar [Mouser](https://www.mouser.com/ProductDetail/Espressif-Systems/ESP32-DevKitC-VB?qs=w%2Fv1CP2dgqq1iFM3SpreoA==) has the official Dev Kit C for $11 USD, looks like they have stock in most countries.

**Comment by darshan-mirajkar** [comment]
Yes I know... I our application hardware we designed PSRAM with the help of expressif. Gerber is ready... Waiting for PCB. So we. Continue on that.

**Comment by h2zero** [comment]
Closing this as resolved.
