### ISSUE TITLE
getServiceUUIDCount() is not defined in NimBLEAdvertisedDevice.cpp

### ISSUE THREAD

**Issue by combatistor** [h2zero/NimBLE-Arduino#114]
I think the title is self explanatory. the method getServiceUUIDCount() is defined in the header NimBLEAdvertisedDevice.h but not implemented in NimBLEAdvertisedDevice.cpp
I am using the latest version of the code.

Thank you

**Comment by h2zero** [comment]
Oops, looks like I lost that one somehow....will fix shortly.

Thanks for reporting!
