### ISSUE TITLE
This library is now added to Arduino library manager.

### ISSUE THREAD

**Issue by h2zero** [h2zero/NimBLE-Arduino#120]
If you prefer to use the Arduino IDE to manage libraries you can now find this repo in it.

Go to sketch -> Include Library -> Manage Libraries and search for NimBLE and install.

**Comment by corneliusmunz** [comment]
@h2zero super! Thanks for your work! Has taken a long time till the library was added by the arduino team since your request but I am happy that it is now available via the library manager 👏🏻👍🏻🏅

**Comment by elguiri** [comment]
@h2zero Great work making this available to the community. The library also appears in PlatformIO (search _NimBLE-Arduino_ in Libraries), also see here https://platformio.org/lib/search?query=NimBLE-Arduino

**Comment by h2zero** [comment]
My pleasure.

I was wondering if it would pop up in platformio automatically or if I had to publish it. Nice to see it was automatic.

**Comment by elguiri** [comment]
> I was wondering if it would pop up in platformio automatically

PlatformIO may lag behind. It's still showing v1.0.0 but I imagine that will update soon!

**Comment by elguiri** [comment]
> PlatformIO may lag behind. It's still showing v1.0.0 but I imagine that will update soon!

Yep, now showing v1.0.1 automatically!

**Comment by h2zero** [comment]
Nice, 1 less thing to do 😃

**Comment by h2zero** [comment]
Closing as stale.
