### ISSUE TITLE
device name character limit

### ISSUE THREAD

**Issue by ccssw** [h2zero/NimBLE-Arduino#141]
Why `void NimBLEDevice::init(const std::string &deviceName)` trunc the string up to 8 characters? I have several devices and I'd like to identify them by their name+mac address (MyDevice-FF:FF:FF:FF:FF:FF). Is it posible?

**Comment by h2zero** [comment]
The name will be truncated to the max characters that will fit in the advertising packet. If you turn on scan response that will provide up to 29 bytes for the device name.

**Comment by ccssw** [comment]
You're right. Thank you!

**Comment by h2zero** [comment]
Glad it works, you're welcome!

**Comment by ccssw** [comment]
You're right. Thank you!
