### ISSUE TITLE
 How can I get which device was disconnected?

### ISSUE THREAD

**Issue by JesusAlexlara** [h2zero/NimBLE-Arduino#147]
I try yo get which device was disconnected, NimBLEServerCallbacks only has "void onConnect(NimBLEServer* pServer, ble_gap_conn_desc* desc)" on the other hand, for disconnection I don't have something similar.
Is there any way to know which device was disconnected?

tanks

**Comment by h2zero** [comment]
Thank you for bringing this up. Currently there is no way to do this through the API but it could be added similarly to the `onConnect()` callback. I will try add this functionality tomorrow.

**Comment by h2zero** [comment]
Hi @JesusAlexlara here is a patch for this if you could please test it and let me know if it works for you. I will push the change to master if it's satisfactory.

[disconnect.txt](https://github.com/h2zero/NimBLE-Arduino/files/5600088/disconnect.txt)

**Comment by JesusAlexlara** [comment]
thank you

**Comment by doudar** [comment]
I'm running into a similar issue where knowing the device that disconnected would be helpful. Thanks for your awesome contribution @h2zero !

**Comment by h2zero** [comment]
@doudar You're welcome. Did you try the patch I posted above? If it's working for you I will merge it into master.

**Comment by doudar** [comment]
I'll see if I can get some time to test it out. Forking right now. It might be a couple days before I can report back as I'll need to modify my code as well and then test for stability.

**Comment by JesusAlexlara** [comment]
My program has been running for several days and everything has worked correctly.

**Comment by h2zero** [comment]
Thanks @JesusAlexlara, I will merge the patch ASAP.

**Comment by doudar** [comment]
I've got about 3 hours of testing in so far. No issues yet either.

**Comment by h2zero** [comment]
Closing as resolved in commit 9074bba.
