### ISSUE TITLE
Connection parameters for a single client; setConnectionParams / updateConnParams

### ISSUE THREAD

**Issue by m-menon** [h2zero/NimBLE-Arduino#149]
Just wondering if you have ever needed to work out the optimal settings for a single client? I am referring to 
`setConnectionParams` (Set initial connection parameters) and `updateConnParams` (Change parameters after connection)

[Example](https://github.com/h2zero/NimBLE-Arduino/blob/cdb7d7839c1406c71cd8a158d28c11f2a970ded1/examples/NimBLE_Client/NimBLE_Client.ino#L171)

Also I have one issue that at the first look seems a bit strange. I am yet to look deeper into this but thought I'd share with you.

I am only connecting to a single device all the while. The actual mac address of my device is 00:a0:50:da:f2:2b but sometimes after the connect/disconnect it shows a different addr. Wondering from where that address(81:00:00:00:00:3f) is coming from.
As a matter of fact the `addr` keeps changing.

```
notifyCB: 00:a0:50:da:f2:2b 49535343-1e4d-4bd9-ba61-23c647249616 handle: 14 value: 8f 00 50 7f 7f 8f 00 50 7f 7f 8f 00 50 7f 7f 8f 00 50 7f 7f
notifyCB: 00:a0:50:da:f2:2b 49535343-1e4d-4bd9-ba61-23c647249616 handle: 14 value: 8f 00 50 7f 7f 8f 00 50 7f 7f 8f 00 50 7f 7f 8f 00 50 7f 7f
notifyCB: 00:a0:50:da:f2:2b 49535343-1e4d-4bd9-ba61-23c647249616 handle: 14 value: 8f 00 50 7f 7f 8f 00 50 7f 7f 8f 00 50 7f 7f 8f 00 50 7f 7f
00:a0:50:da:f2:2b disconnected!
E NimBLEClient: "Error: Failed to connect to device; " "addr=81:00:00:00:00:3f, rc=3; "
Failed to connect
failed
E NimBLEClient: "Error: Failed to connect to device; " "addr=6f:6e:6f:4d:73:6e, rc=3; "
Failed to connect
failed
00:a0:50:da:f2:2b disconnected!
Failed to connect
failed
E NimBLEClient: "Error: Failed to connect to device; " "addr=53:00:00:00:00:00, rc=3; "
Failed to connect
failed
```
I can post this as a separate issue but I thought I'll post the above additional info.

**Comment by h2zero** [comment]
The device you are connecting to has a random address that changes every X minutes. You would need to bond with it in order to resolve the address and use it's ID address instead. I've been working on this locally and hope to provide a solution soon.

Optimal connection parameters depends on the application. If connecting to a battery powered device I keep the interval long to save power. If you need more data throughput you should keep it shorter. Mostly a matter of the situation and preference.

**Comment by m-menon** [comment]
@h2zero thanks for the pointers. I will try different values and see how it goes.
