### ISSUE TITLE
setting default mtu / conn paramaters

### ISSUE THREAD

**Issue by foofel** [h2zero/NimBLE-Arduino#153]
Hey,

I am using this library to send hx711 (load sensor) data via bluetooth and it works very well, as the hx711 can read up to 80hz i need to decrease the connection time, i am currently doing this in the 
`void onConnect(NimBLEServer* pServer, ble_gap_conn_desc* desc);`
function but is this the correct way? Is it possible to specify my desired default params so they are automatically set on the connection startup? Also i need a larger mtu, i currently handle this on the client side but this forces the client to know the mtu size, is it possible to set the default mtu on the server side?

Best

**Comment by h2zero** [comment]
The connection parameters are controlled by the client, the server can request parameters and the client can reject or accept them, no guarantees. The MTU can be set after calling `NimBLEDevice:init()` by calling 'NimBLEdevice::setMTU()` but the lowest value between the client and the server will be selected.

**Comment by h2zero** [comment]
@foofel any updates on this?

**Comment by h2zero** [comment]
Closing as stale, please re-open if you have further issues.

**Comment by foofel** [comment]
Oh sorry didn't see your comment (little late now), it works perfectly as you describe with the client requesting the mtu. also setting the connection parameters work. thanks for the great library! :)

**Comment by jojo0329** [comment]
@h2zero ,Hey,I'm having the same problem, I need to set my mtu to 1024. however the client set it and it can only be set to 255，although i calling 'NimBLEdevice::setMTU()`！

**Comment by h2zero** [comment]
The MTU can be a maximum of 512 as per BLE specifications. Both the client and the server need to support this value and if not the lowest value supported between the devices will be used.

**Comment by jojo0329** [comment]
> 



> The MTU can be a maximum of 512 as per BLE specifications. Both the client and the server need to support this value and if not the lowest value supported between the devices will be used.
Thanks for the reply, I did in fact pay attention to that. Even though I've supported 1024mtu in my code, I set 1024 in the app and it still doesn't modify the value of mtu, it becomes 255 instead
`BLEDevice::init("BZ");
// ADDED to support larger MTU
    NimBLEDevice::setMTU(1024);//test
// Create the BLE Server`
<img src="https://github.com/h2zero/NimBLE-Arduino/assets/139374318/d89e5d7a-b111-4528-8444-ae077c341a90" width="30%">

**Comment by h2zero** [comment]
The controller of each device will reject such values that is why you're not seeing it change. Try it with 512 and see if it changes to that.
