### ISSUE TITLE
expose "bool response=false" from writeValue in setValue(..., bool response=false)

### ISSUE THREAD

**Issue by fightforlife** [h2zero/NimBLE-Arduino#157]
Hi there, 

would it be possible to expose the parameter  `bool response=false"` 
from `NimBLEremoteCharacteristics::writeValue (const std::string &newValue, bool response=false)` 
as an optional (fourth) parameter in 
`NimBLEClient::setValue (const NimBLEUUID &serviceUUID, const NimBLEUUID &characteristicUUID, const std::string &value, bool response=false)`

Some of my devices only work with bool response=true. (e.g. eQ3 ble thermostats)
And this would really help to declutter alot of my code.

Thanks in advance!

**Comment by h2zero** [comment]
Sure, that could be added easily enough. If you want to make a PR for it please do so. Otherwise I can add it with the other updates this weekend.

**Comment by h2zero** [comment]
@fightforlife this has been added in commit 135e2fa. Please let me know if this works for you.

**Comment by h2zero** [comment]
Closing this as resolved.

**Comment by fightforlife** [comment]
Thank you very much. I just had time to test this and it is working as expceted!
