### ISSUE TITLE
h2zero works too hard closing issues and needs a beer :)

### ISSUE THREAD

**Issue by doudar** [h2zero/NimBLE-Arduino#163]
See title^^

Seriously, are you even human? :)

You can only close this after you schedule a little h2zero time.

**Comment by h2zero** [comment]
I can drink beer and close issues at the same time 🥂 😆.

Just going through things to remind myself what needs to be done for the upcoming release, good time to cleanup too.

**Comment by doudar** [comment]
Nicely done!![image](https://user-images.githubusercontent.com/17362216/103253076-4db1c880-4945-11eb-8a08-69e04ed2f4f9.jpeg)

I'm printing new parts I designed today and drinking beer and watching you close issues. Enjoy your night!

**Comment by h2zero** [comment]
Haha, awesome. Can't say I've seen that beer but I'd buy it if I did! 

Thanks for the reminder, I need to print a few things as well.

**Comment by doudar** [comment]
Me too. Had to. 

If you ever need an excuse to print parts, head over to my smart spin. Lots of stuff to print, lots of code that needs more contributors.

**Comment by h2zero** [comment]
Actually I need more excuses not to 😄 I will check out the repo for sure!

**Comment by doudar** [comment]
Haha! Exactly!

**Comment by chegewara** [comment]
This is the way BLE library has been "outsourced" from Kolbans repo ;)
