### ISSUE TITLE
NimBLEScan : NimBLEAdvertisedDevice getpayload() returns incomplete packet

### ISSUE THREAD

**Issue by justoke** [h2zero/NimBLE-Arduino#165]
Using an ESP32 and the example scan code, I have noticed a difference in the payload length compared with the original nkolban library. I used the example scan code from both this library and the nkolban one and for one device I got a different length payload. It appears that part of the payload is missing or incomplete as I have compared the expected data with the manufacturer's data sheet and the payload seems to have skipped about 30 bytes. 

From the snippet below - the payload starts at the two 16s onwards, whereas the full payload is expected:
![image](https://user-images.githubusercontent.com/26506785/103278923-86dd4d80-49c4-11eb-8be8-fe1fbc2a149a.png)

I have another type of sensor which is decoded the same for both this library and the nkolban one, so maybe some logic there for iBeacon types, which the first sensor is of this type. This issue fortunately is easy to deal with as the actual data is in the portion of the payload that is retrieved.

**Comment by h2zero** [comment]
I'm working on a solution to this. What happens is NimBLE sends the payload for the scan response data separately and after the advertisement packet was received so the payload data gets overwritten with just the scan response data.
