### ISSUE TITLE
Ignore ble device temporarily during scan (time limit)

### ISSUE THREAD

**Issue by m-menon** [h2zero/NimBLE-Arduino#168]
Something I am trying to figure out the best way to achieve - During the BLE scan sometimes I need to ignore a device for a short duration (2-3-4 seconds perhaps). I am storing the time that the device was first found and then subsequently ignoring if the ble device is found again (during the same scan, cos the scan duration is like 8-10 seconds). But the scan won't report the same device (during the same scan) unless I set the find duplicates to  true. Is there a way to achieve this without having to set the find duplicates=true cos that will mess up some other parts of my program. Any tips will be of great while I try to figure out the different ways. Thanks.

Just found something as I just started to figure out some other ways;

Could I use the  `NimBLEScan::erase(const NimBLEAddress &address)` or something  in the scan callback itself? I thought I'd post this while I try that out because I am not sure if it's a good idea to erase something within the scan callback itself ... anyways I am experimenting. But on the surface `NimBLEScan::erase(const NimBLEAddress &address)` kinda seems to be able to do what I am looking for

The above solution seems to work. I just had to ensure that I don't process anything further in that callback otherwise it would reference something that has been erased and that could obviously crash the mcu. Thanks a lot for this great library. The original ESP32 BLE library is fantastic and this library has taken it up further a few notches. Closing this now and thank you wonderful people out there.

**Comment by h2zero** [comment]
Hi @m-menon, yes, in fact the callback is the best place to do that as no further scan results will come until you return from the callback so it is unlikely to conflict.

As to ignoring for a duration, this could be done with a task, perhaps triggered after the first result in the callback. 
In the task you could check `NimBLEDevice::isIgnored()` and if false call `::addIgnored()` delay for x time and then `::removeIgnored()`.

**Comment by m-menon** [comment]
> Hi @m-menon, yes, in fact the callback is the best place to do that as no further scan results will come until you return from the callback so it is unlikely to conflict.
> 
> As to ignoring for a duration, this could be done with a task, perhaps triggered after the first result in the callback.
> In the task you could check `NimBLEDevice::isIgnored()` and if false call `::addIgnored()` delay for x time and then `::removeIgnored()`.

Fantastic! Thanks for that solution. I will check that out.
