### ISSUE TITLE
Return code from NimBLEScan::start is always 0

### ISSUE THREAD

**Issue by pletch** [h2zero/NimBLE-Arduino#175]
Since the addition of commit [413e64640946195bf5f68c384279a615aefe8600](https://github.com/h2zero/NimBLE-Arduino/commit/413e64640946195bf5f68c384279a615aefe8600), NimBLEScan::start always gives a return code of 0.  

Using the following function to initiate a scan and always exit through 'the scan failed to start' branch since this commit added.

```
bool tiltScanner::scan()
{
    if (!pBLEScan->isScanning())  // Check if scan already in progress
    //Try to start a new scan
    {
        pBLEScan->clearResults();   
        if (pBLEScan->start(BLE_SCAN_TIME, nullptr, true))  //This no longer ever returns true...possibly a bug?? 
        {
            Serial.println("Scan started.");
            return true;  //Scan successfully started.
        }
        else
        {
            Serial.println("Scan failed to start.");
            return false;  //Scan failed to start.
        }
    }
    return false;
}
```

**Comment by h2zero** [comment]
Any error messages, debug log? Nothing in this respect should have changed for you in that commit.

**Comment by h2zero** [comment]
I see the problem, sorry about that [this line](https://github.com/h2zero/NimBLE-Arduino/blob/737de67bc68cdd86a37f3efaea3c00aed9b17997/src/NimBLEScan.cpp#L307) should have been `&&` not `||` .

Fix incoming now.

**Comment by pletch** [comment]
Great!  Thank you for the quick fix.

**Comment by h2zero** [comment]
Fixed :), thanks for the report!
