### ISSUE TITLE
silly question - when can I start a scan?

### ISSUE THREAD

**Issue by btsimonh** [h2zero/NimBLE-Arduino#188]
Hi H2zero,

sorry to bug you again,  this is probably obvious to 'one skilled in the art'.

A problem I have is wanting to hear adverts at the same time as having connected, and doing an 'operation' (read/write, await notify).

At the moment, the scan is automatically stopped when a connection is attempted.
I don't restart scanning until I have disconnected.

Can I restart scanning whilst still connected?  If so, in what phase?

br,

Simon.

(use case - connecting to devices to poll them for info, but still wanting to hear adverts for presence monitoring).

**Comment by h2zero** [comment]
You sure can, that's what the NimBLE_Client example does. You can start scanning anytime after the connect call returns.

**Comment by btsimonh** [comment]
thankyou :), seems to be working.
At a lower level, could the scan theoretically be started earlier, or not need to stop?
(for distant devices, the connect can take a *long* time to fail)....

**Comment by h2zero** [comment]
The connection process uses the scan to find the device so the discovery scan needs to stop while attempting connection.

**Comment by chegewara** [comment]
Connection process is using a lot ble radio, so it is not possible to continue scan at the same time.

**Comment by btsimonh** [comment]
thanks both, it's fairly clear now :)
