### ISSUE TITLE
Missing documentation pages

### ISSUE THREAD

**Issue by elguiri** [h2zero/NimBLE-Arduino#190]
Hi @h2zero  hope all is well

Not sure if it is an issue on my side, but there are classes missing from the documentation eg this page gives a 404 error
https://h2zero.github.io/esp-nimble-cpp/class_nim_b_l_e_scan.html

**Comment by h2zero** [comment]
All good here, hope the same for you.

Thank you for reporting, it's definitely broken. I'll look into this right away.

**Comment by h2zero** [comment]
Should be fixed now, let me know if you have any more problems.

**Comment by elguiri** [comment]
@h2zero Yep all looks good, closing this issue thanks!
