### ISSUE TITLE
CI testing when using NimBLE-Arduino

### ISSUE THREAD

**Issue by kadaan** [h2zero/NimBLE-Arduino#213]
I'd like to test our application and we use NimBLE-Arduino heavily.  I'm trying to extract as much code as possible and write it as a cross platform library.  This will enable us to write "native" tests in platformio and run them as part of PR process in our project.  

The stumbling block right now is that most (all?) of NimBLE-Arduino requires Arduino (surprised, nope...).  Even classes like NimBLEUUID, which I think could be cross platform.

So...

1. Can NimBLEUUID.h be made to not require "sdkconfig.h"?
2. Is there another way to use NimBLEUUID.h in cross platform code?
3. Do you have other ideas for testing projects that depend on NimBLE-Arduino?

**Comment by h2zero** [comment]
If you are using ESP-IDF you could simply use the [esp-nimble-cpp repo](https://github.com/h2zero/esp-nimble-cpp). Arduino is not required for that and is a mirror of this repo but configured without Arduino. 

If you are trying to use this for a different MCU platform... stay tuned

**Comment by kadaan** [comment]
The project is for ESP32, but I’d like to do the bulk of the testing on Linux, Mac, etc.  To do this I’m extracting out a custom library and not depending on FreeRTOS, Arduino, ESP specific libraries, etc.  Much of the library will be dealing with incoming and outgoing BLE data. 

So, what I’m looking for is a way to use NimBLEUUID (maybe other classes later) in the library. That library could be build on a Linux box and tested. It will also be compiled into the Arduino program that is run on an ESP32. 

FYI, this is in regard to testing SmartSpin2K

**Comment by h2zero** [comment]
In that case it should be a simple matter of creating and sdkconfig.h file in the library folder with one line in it: `#define CONFIG_BT_ENABLED`.
The only other place where there might be an issue is with some freertos specific things (esp mutexes and task notifications) NimBLEUUID and others should be fine however.

**Comment by kadaan** [comment]
Cool. That was what I was thinking or trying next. Thanks!

**Comment by kadaan** [comment]
This is kinda working, but you are correct the FreeRTOS dependency makes this a PITA

**Comment by h2zero** [comment]
Yep, you can look into the linux port for NimBLE https://github.com/apache/mynewt-nimble/tree/master/porting/npl/linux
and run the freertos simulator https://en.freertos.org/FreeRTOS-simulator-for-Linux.html 
and of course you would want to use the esp-nimble-cpp library. I have not tried this and just found that simulator recently but it should work on Mac as well. Would be interested to hear if you try it.

**Comment by kadaan** [comment]
Looks like I'm getting there slowly...  It is difficult in PlatformIO to pull in just the FreeRTOS pieces needed, so I created an ArduinoCompat library with the correct code in it. My native environment looks like: 
```
[env:native]
platform = native
lib_deps = 
	https://github.com/h2zero/esp-nimble-cpp.git#master
	lib/ArduinoCompat
	lib/SS2K
build_flags =
    -std=c++11
```

The issue now is that when it pulls your `esp-nimble-cpp` repository I end up with only:
![image](https://user-images.githubusercontent.com/1904898/113255202-64392a00-927c-11eb-8199-880096016b13.png)

Any idea why it wouldn't pull your whole repo?

**Comment by kadaan** [comment]
I don't want to duplicate files, but this is a ton of hoops to go through to just get NimBLEUUID :P

**Comment by kadaan** [comment]
For now, I ended up just creating ArduinoCompat like:
![image](https://user-images.githubusercontent.com/1904898/113263546-c434ce00-9286-11eb-83b2-bdc02e96edd8.png)

It sucks, because I have to have a full copy of `NimBLEUUID` in there, but hopefully it will not need to grow beyond that.  I plan to leave all the actual BLECharacteristic reading and writing to the Arduino application, but using the library to do all the heavy lifting.

If you figure out how to wire this all up more cleanly (likely with linux nimble, nimble-cpp, and the freertos sim), let me know.

**Comment by kadaan** [comment]
@h2zero Here is how I ended up doing it.  This works because the goal of the library it to have a very slim connection to BLE.

https://github.com/doudar/SmartSpin2k/pull/171

**Comment by h2zero** [comment]
Good work! Thanks for the reference.

**Comment by kadaan** [comment]
> Any idea why it wouldn't pull your whole repo?

Looks like this is a platformio bug
