### ISSUE TITLE
'class NimBLEServer' has no member named 'getConnId'

### ISSUE THREAD

**Issue by societyofrobots** [h2zero/NimBLE-Arduino#216]
I'm converting from the older BLE to NimBLE, but got this one compile error I can't figure out.

This works in the old version:
`pServer->disconnect(pServer->getConnId());`

But in NimBLE gives me this error:
`'class NimBLEServer' has no member named 'getConnId'`

**Comment by h2zero** [comment]
Sorry for the trouble. This was not implemented due to multi-connection support. Instead you should store the connection ID from the `onConnect` callback and use it directly with this function. I hope to update this in the future to support other methods.

**Comment by h2zero** [comment]
Just pushed a commit yesterday that addresses this 206cb3d4af100265c92dd568dafbc23736f94e5e.

**Comment by societyofrobots** [comment]
I ended up using this and it solved my issue:
`NimBLEDevice::getClientByID(desc->conn_handle)->disconnect();`
