### ISSUE TITLE
setValue() only sends 252 bytes of data

### ISSUE THREAD

**Issue by ln-12** [h2zero/NimBLE-Arduino#219]
While playing around with the [uart example](https://github.com/h2zero/NimBLE-Arduino/blob/76ce18a10f29cfbda991e00467f442d142e7384b/examples/Refactored_original_examples/BLE_uart/BLE_uart.ino) in the library, I noticed that [`setValue(const std::string &value)`](https://github.com/h2zero/NimBLE-Arduino/blob/76ce18a10f29cfbda991e00467f442d142e7384b/src/NimBLEDescriptor.h#L57) only transmits 252 bytes of data. Is there any reason why it's not 512? How would I send 512 bytes at once?

**Comment by h2zero** [comment]
Hi, you will need to change the MTU size. `NimBLEDevice::setMTU(517)` (note that you need to use 517 for 512 bytes due to header info). Both devices will need to support this MTU as well.

**Comment by ln-12** [comment]
It works now. Thank you very much for your fast response! :)

**Comment by joseitor** [comment]
I can't sent more than 20 bytes by notification. Can you share your code? Even using `NimBLEDevice::setMTU(517)`, nothing change.
