### ISSUE TITLE
Forget pairing/bonding information

### ISSUE THREAD

**Issue by ketan** [h2zero/NimBLE-Arduino#224]
Hi:

Is there any API to forget any pairing and bonding information that is persisted on the ESP32 flash/nvram storage?

Thanks.

**Comment by h2zero** [comment]
Hi @ketan, I'm working on the API for this right now actually. However, for the time being you can simply call `ble_store_clear();`

**Comment by ketan** [comment]
Thanks!

**Comment by h2zero** [comment]
Just to update this, the API has now been added in d1d7db7
