### ISSUE TITLE
Suggestions needed for next release!

### ISSUE THREAD

**Issue by h2zero** [h2zero/NimBLE-Arduino#229]
Hi all, I'm looking for some suggestions to include with the next release. This is predicted to be the last release of 1.x.x that will maintain the current compatibility with the Arduino core BLE library, in release 2.x.x all the deprecated classes/functions will be removed/replaced.

Currently on my todo list is:
- ~~[Server] Add indexing/iterating of connected clients to get their information.~~ done
- ~~[Server] Statically create characteristics/descriptors and expose addCharacteristic/addDescriptor methods.~~ done #234
- ~~[Client] Improve descriptor retrieval by UUID reliability.~~ done #233 
- ~~[Scan] Invoke callback for any advertised devices that have not invoked it when scan is stopped manually.~~ Won't do; problematic
- ~~[general] Update core to NimBLE 1.3.0 / IDF master + cleanup logging~~ done

I'd like to put more on this list before I break stuff, please post your suggestions/desires/comments in this issue.

**Comment by thorrak** [comment]
Are there already `#warning`'s for the deprecated items that are going away? 

I don't recall seeing anything in _my_ use of the library, but it might be that I'm not using enough of the old functionality...

**Comment by h2zero** [comment]
Yes, all the affected items have been marked deprecated for quite a while now. If you've been compiling with -Wall you would have seen them. 

To be clear, nothing major in respect to compatibility is planned to change beyond what has been deprecated already but there may be some minor tweaks to the API as testing requires.

**Comment by h2zero** [comment]
Adding to my list:
Whitelist scan/advertising/connection support.
