### ISSUE TITLE
NimBLEDevice cannot be re-initialized after call to deinit()

### ISSUE THREAD

**Issue by thorrak** [h2zero/NimBLE-Arduino#23]
When `NimBLEDevice::init("")` is called after a call to `NimBLEDevice::deinit()`, the reinitialization fails and BLE scans cannot take place.

**Comment by h2zero** [comment]
Thanks, it's been a while since I tested this. I'll have a look.

**Comment by h2zero** [comment]
Just pushed a fix for this, reopen if you have anymore issues.
