### ISSUE TITLE
Pin security not working on android

### ISSUE THREAD

**Issue by schlaegerz** [h2zero/NimBLE-Arduino#232]
I have pin security set up

```
 NimBLEDevice::setSecurityIOCap(BLE_HS_IO_DISPLAY_ONLY); // set display output capability
 NimBLEDevice::setSecurityAuth(true, true, true);
  _pin = esp_random() % 9000 + 1000
  
  
  
uint32_t BluetoothAccessPoint::onPassKeyRequest()
{
    ESP_LOGI(TAG, "Server PassKeyRequest");
    
    show_pin_to_ui(_pin);
    return _pin;
};


void BluetoothAccessPoint::onAuthenticationComplete(ble_gap_conn_desc *desc)
{
    ESP_LOGI(TAG, "On auth complete enc: %d aut: %d bond: %d key: %d", desc->sec_state.encrypted,
             desc->sec_state.authenticated,
             desc->sec_state.bonded,
             desc->sec_state.key_size);
    if (!desc->sec_state.encrypted)
    {
        NimBLEDevice::getServer()->disconnect(desc->conn_handle);
        ESP_LOGI(TAG, "Encrypt connection failed - disconnecting client");
        return;
    }
    ESP_LOGI(TAG, "Starting BLE work!");
}

```

And on android I do correctly get the pin pop-up to show up, but when I put in the pin it always fails and desc->sec_state.authenticated is set to 0.

Oddly on ios is works just fine, so I'm not sure what could be going wrong specifically on android.

I'm using a Galaxy S9 on Android 9

onPassKeyRequest(): Server PassKeyRequest, 9591 9591
D NimBLEServer: "BLE_SM_IOACT_DISP; ble_sm_inject_io result: 0"
D NimBLEServer: "<< handleGATTServerEvent"
D NimBLEServer: ">> handleGapEvent: "
D NimBLEServer: "Connection parameters updated."
D NimBLEServer: ">> handleGapEvent: "
[I][BlueToothAccessPoint.cpp:283] onAuthenticationComplete(): On auth complete enc: 0 aut: 0 bond: 0 key: 0

 Are there any ideas?

**Comment by schlaegerz** [comment]
This is with the basic Android Bluetooth settings. Just when I try to connect to the device.

Also happens with my own app and BLE scanner app

**Comment by h2zero** [comment]
I just noticed why you are having this issue. Your pin code is only 4 digit, you need 6 in BLE. iOS probably prepends 2 zeros in front of the passkey.

**Comment by schlaegerz** [comment]
Oh that was it! Making me go crazy, no idea why I thought it should be 4 pins.

Thanks so much!
