### ISSUE TITLE
`OnConfirmPIN` is not called even if `BLE_HS_IO_DISPLAY_YESNO` is specified

### ISSUE THREAD

**Issue by wakwak-koba** [h2zero/NimBLE-Arduino#260]
When I uncommented line 160 of `examples/NimBLE_Server/NimBLE_Server.ino`, enabled it, and compiled it, I thought that `ServerCallbacks::onConfirmPIN()` would be called, but it was never called and `ServerCallbacks::onPassKeyRequest()` would be called.

https://github.com/h2zero/NimBLE-Arduino/blob/e9bda73e88d42b5b18d2cf1c64e3c708e7ee17b0/examples/NimBLE_Server/NimBLE_Server.ino#L160

How can I get `ServerCallbacks::onConfirmPIN()` to be called?

```
08:17:36.923 -> Advertising Started
08:17:53.205 -> D NimBLEServer: ">> handleGapEvent: BLE_GAP_EVENT_CONNECT "
08:17:53.205 -> Client connected
08:17:53.205 -> Multi-connect support: start advertising
08:17:53.205 -> D NimBLEAdvertising: ">> Advertising start: customAdvData: 0, customScanResponseData: 0"
08:17:53.205 -> D NimBLEAdvertising: "<< Advertising start"
08:17:53.205 -> Client address: 52:f8:3a:6d:5c:b9
08:17:53.343 -> D NimBLEServer: ">> handleGapEvent: BLE_GAP_EVENT_CONN_UPDATE_REQ"
08:17:53.343 -> D NimBLEServer: "<< handleGATTServerEvent"
08:17:53.390 -> D NimBLEServer: ">> handleGapEvent: BLE_GAP_EVENT_PASSKEY_ACTION"
08:17:53.390 -> D NimBLEServerCallbacks: "onPassKeyRequest: default: 123456"
08:17:53.390 -> Server Passkey Request
08:17:53.390 -> D NimBLEServer: "BLE_SM_IOACT_DISP; ble_sm_inject_io result: 0"
08:17:53.390 -> D NimBLEServer: "<< handleGATTServerEvent"
08:17:53.668 -> D NimBLEServer: ">> handleGapEvent: BLE_GAP_EVENT_CONN_UPDATE"
08:17:53.714 -> D NimBLEServer: "Connection parameters updated."
```

**Comment by h2zero** [comment]
Did you also change `NimBLEDevice::setSecurityAuth(/*BLE_SM_PAIR_AUTHREQ_BOND | BLE_SM_PAIR_AUTHREQ_MITM |*/ BLE_SM_PAIR_AUTHREQ_SC);` to require `BLE_SM_PAIR_AUTHREQ_MITM `?

Such as: NimBLEDevice::setSecurityAuth(BLE_SM_PAIR_AUTHREQ_MITM | BLE_SM_PAIR_AUTHREQ_SC);`

**Comment by wakwak-koba** [comment]
Even with `NimBLEDevice::setSecurityAuth(BLE_SM_PAIR_AUTHREQ_MITM | BLE_SM_PAIR_AUTHREQ_SC);`, `onPassKeyRequest()` will be called.

**Comment by h2zero** [comment]
That is strange, I will test this and see what could be happening.

**Comment by wakwak-koba** [comment]
I was testing with two Android Phones and started ordering for the following points:
https://github.com/h2zero/NimBLE-Arduino/blob/e9bda73e88d42b5b18d2cf1c64e3c708e7ee17b0/src/nimble/host/src/ble_sm_sc.c#L56-L79

I feel that `BLE_SM_IOACT_DISP` has been chosen as a compromise between the server and the client.

I'd like to check the values ​​of both `io_caps`, but how do I enable BLE_HS_LOG under Arduino?

**Comment by h2zero** [comment]
It seems that the client device you are using does not support BLE secure connections (numeric comparison).

**Comment by wakwak-koba** [comment]
I placed BLE_HS_LOG here and there and tested it.
As you can guess, the Android Phone I used for my test didn't support Secure-mode and apparently only connected with Legacy.

https://github.com/h2zero/NimBLE-Arduino/blob/e9bda73e88d42b5b18d2cf1c64e3c708e7ee17b0/src/nimble/host/src/ble_sm_lgcy.c#L38-L60

I thought it would be useful to have an easy way to check the IOCAPs and ble_sm_proc.flags of the other terminal.

This issue is resolved. 
I'm sorry for making a noise...
