### ISSUE TITLE
NimBLE with BluetoothSerial error with device rebooting

### ISSUE THREAD

**Issue by govnocoder** [h2zero/NimBLE-Arduino#268]
`#include <NimBLEDevice.h>

//#include <BLEDevice.h>
//#include <BLEUtils.h>
//#include <BLEScan.h>
//#include <BLEAdvertisedDevice.h>
#include "BluetoothSerial.h"

BluetoothSerial SerialBT;
NimBLEScan* pBLEScan;

class MyAdvertisedDeviceCallbacks: public NimBLEAdvertisedDeviceCallbacks {
    void onResult(NimBLEAdvertisedDevice* advertisedDevice) {
      Serial.printf("Advertised Device: %s \n", advertisedDevice->toString().c_str());
      String sensorName = advertisedDevice->getName().c_str();
      String address = advertisedDevice->getAddress().toString().c_str();
      String manufacturerData = advertisedDevice->getManufacturerData().c_str();
      SerialBT.println("Name: " + sensorName);
      SerialBT.println("Address: " + address);
      SerialBT.println("Manufacturer data: " + manufacturerData);
    }
};

void setup() {
  Serial.begin(115200);
  Serial.println("Scanning...");
  if (!SerialBT.begin("ODB")) {
    Serial.println("An error occurred initializing Bluetooth");
  } else {
    Serial.println("Bluetooth initialized");
  }
  NimBLEDevice::setScanFilterMode(CONFIG_BTDM_SCAN_DUPL_TYPE_DEVICE);

  
  NimBLEDevice::init("");
  pBLEScan = NimBLEDevice::getScan(); //create new scan
  // Set the callback for when devices are discovered, no duplicates.
  pBLEScan->setAdvertisedDeviceCallbacks(new MyAdvertisedDeviceCallbacks(), false);
  pBLEScan->setActiveScan(true); // Set active scanning, this will get more data from the advertiser.
  pBLEScan->setInterval(97); // How often the scan occurs / switches channels; in milliseconds,
  pBLEScan->setWindow(37);  // How long to scan during the interval; in milliseconds.
  pBLEScan->setMaxResults(0); // do not store the scan results, use callback only.
}

void loop() {
  // If an error occurs that stops the scan, it will be restarted here.
  if(pBLEScan->isScanning() == false) {
      // Start scan with: duration = 0 seconds(forever), no scan end callback, not a continuation of a previous scan.
      pBLEScan->start(0, nullptr, false);
  }

  delay(2000);
}`

With this sketch my esp32 rebooting with error:

> 16:32:17.554 -> Scanning...
> 16:32:18.020 -> Bluetooth initialized
> 16:32:18.020 -> ESP_ERROR_CHECK failed: esp_err_t 0x103 (ESP_ERR_INVALID_STATE) at 0x4008f1ec
> 16:32:18.020 -> file: "C:\Users\Vladimir\Documents\Arduino\libraries\NimBLE-Arduino-master\src\NimBLEDevice.cpp" line 769
> 16:32:18.068 -> func: static void NimBLEDevice::init(const string&)
> 16:32:18.068 -> expression: esp_bt_controller_init(&bt_cfg)
> 16:32:18.068 -> 
> 16:32:18.068 -> ELF file SHA256: 0000000000000000
> 16:32:18.068 -> 
> 16:32:18.068 -> Backtrace: 0x4008ecd4:0x3ffc8a30 0x4008f1ef:0x3ffc8a50 0x400d33b9:0x3ffc8a70 0x400d1a09:0x3ffc8ab0 0x400e4afa:0x3ffc8b00 0x4008ffc6:0x3ffc8b20
> 16:32:18.068 -> 
> 16:32:18.068 -> Rebooting...
> 16:32:18.068 -> ets Jun  8 2016 00:22:57
> 16:32:18.068 -> 
> 16:32:18.068 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> 16:32:18.068 -> configsip: 0, SPIWP:0xee
> 16:32:18.068 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> 16:32:18.068 -> mode:DIO, clock div:1
> 16:32:18.068 -> load:0x3fff0018,len:4
> 16:32:18.115 -> load:0x3fff001c,len:1216
> 16:32:18.115 -> ho 0 tail 12 room 4
> 16:32:18.115 -> load:0x40078000,len:10944
> 16:32:18.115 -> load:0x40080400,len:6388
> 16:32:18.115 -> entry 0x400806b4
> 16:32:18.398 -> Scanning...
> 16:32:18.911 -> Bluetooth initialized
> 16:32:18.911 -> ESP_ERROR_CHECK failed: esp_err_t 0x103 (ESP_ERR_INVALID_STATE) at 0x4008f1ec
> 16:32:18.911 -> file: "C:\Users\Vladimir\Documents\Arduino\libraries\NimBLE-Arduino-master\src\NimBLEDevice.cpp" line 769
> 16:32:18.911 -> func: static void NimBLEDevice::init(const string&)
> 16:32:18.911 -> expression: esp_bt_controller_init(&bt_cfg)
> 16:32:18.911 -> 
> 16:32:18.911 -> ELF file SHA256: 0000000000000000
> 16:32:18.911 -> 
> 16:32:18.911 -> Backtrace: 0x4008ecd4:0x3ffc8a30 0x4008f1ef:0x3ffc8a50 0x400d33b9:0x3ffc8a70 0x400d1a09:0x3ffc8ab0 0x400e4afa:0x3ffc8b00 0x4008ffc6:0x3ffc8b20
> 16:32:18.959 -> 
> 16:32:18.959 -> Rebooting...

Without NimBLE this code working fine.

**Comment by h2zero** [comment]
Closing as Bluetoothserial (classic) is not supported by NimBLE.
