### ISSUE TITLE
Abort client connection

### ISSUE THREAD

**Issue by itamardv** [h2zero/NimBLE-Arduino#285]
Hi All,

NimBLE is a great lib. Very good work of the developers. Congratulations !

I'd like to know if there is some way to abort a client connection at  onConnect callback of NimBle Server.

Thanks!

**Comment by h2zero** [comment]
Hi and thank you.

Yes, you can use this:
```
void onConnect(NimBLEServer* pServer, ble_gap_conn_desc* desc) {
    if (your check value status etc.. here) {
        pServer->disconnect(desc->conn_handle);
    }
}
```

**Comment by itamardv** [comment]
Great h2zero !

This will disconnect only the present client trying to connect right?
Previously connected clients will be preserved ?

Thnaks

**Comment by h2zero** [comment]
Yes, it will disconnect only the currently connecting client.

**Comment by h2zero** [comment]
Closing as resolved.
