### ISSUE TITLE
client example Words used

### ISSUE THREAD

**Issue by svdrummer** [h2zero/NimBLE-Arduino#290]
Hi,
I am trying to look for a list of devices and find the battery voltage of the beacon.
I look at the example called Nimble_client and can see the words "DEAD", "BEEF" "TASTY"

Does anyone know what these even mean"

One device I am looking for has service UUID of abbaff00-e56a-484c-b832-8b17cf6cbfe8
service is !*)A
Characteristic of 2A29

no idea what the rest means.
It is a fitbit watch
TIA

**Comment by chegewara** [comment]
> I look at the example called Nimble_client and can see the words "DEAD", "BEEF" "TASTY"

its just a funny usage hex values (0-9, A-F) to create UUID (TASTY is characteristic value, so it can use any chars).

**Comment by svdrummer** [comment]
Dead beef feed i get that part 😀 to read a battery voltage, can anyone recommend the standard uuid or whatever for battery voltages

**Comment by h2zero** [comment]
The battery service standard uuid is 0x180F.

The 0x180a you see above is device information service.

You can see the full list of assigned numbers here:

https://btprodspecificationrefs.blob.core.windows.net/assigned-values/16-bit%20UUID%20Numbers%20Document.pdf

**Comment by h2zero** [comment]
Closing this as a non-library issue. Please reopen as a discussion if necessary.
