### ISSUE TITLE
Problem with bonding with BLE server device

### ISSUE THREAD

**Issue by PORTB** [h2zero/NimBLE-Arduino#301]
I am trying to interact with a BLE light switch I have. It has a characteristic that can be written to (or read) to control the state of it (on/off). I can connect to it using my android phone (with nrf connect). When I try to read or write the characteristic, it immediatley asks to pair/bond with the lightswitch if it hasn't been bonded. Notifications from the service work without bonding. The problem is, I can't get my ESP32 to bond with the device. I have made a program that tries to interact with the switch, but reading doesn't work (always returns 0) and writing doesn't work, but notifications work fine. This is my program:
```cpp
#include <Arduino.h>

#include <NimBLEDevice.h>
#include <ESPAsyncWebServer.h>
#include <NimBLEUtils.h>

BLEUUID ControlServiceUUID("720a9080-9c7d-11e5-a7e3-0002a5d5c51b");
BLEUUID OnOffCharacteristicUUID("720a9081-9c7d-11e5-a7e3-0002a5d5c51b");

BLEAddress LightSwitchAddr("84:2e:14:79:2f:f1");//00:0D:6F:04:5F:B1

BLEClient* client;
BLERemoteService* controlService;
BLERemoteCharacteristic* onOffCharacteristic;

constexpr auto LED_PIN = LED_BUILTIN;

const char* const boolToString(const bool& b)
{
    if(b)
        return "true";
    else
        return "false";
}

void onOffStateNotified(BLERemoteCharacteristic* pBLERemoteCharacteristic, uint8_t* pData, size_t length, bool isNotify);

void setup() 
{
    Serial.begin(115200);
    pinMode(LED_PIN, OUTPUT);

    //BLEDevice::setEncryptionLevel(esp_ble_sec_act_t::ESP_BLE_SEC_ENCRYPT_NO_MITM);
    BLEDevice::init("Fuf");
    NimBLEDevice::setSecurityAuth(true, false, true);

    client = BLEDevice::createClient();

    if(!client->connect(LightSwitchAddr))
    {
        Serial.println("Could not connect");

        while(1); 
    }

    BLEDevice::startSecurity(client->getConnId());

    Serial.printf("Bond Status: %s\n", BLEDevice::isBonded(LightSwitchAddr) ? "bonded" : "not bonded");

    client->secureConnection();

    controlService = client->getService(ControlServiceUUID);
    onOffCharacteristic = controlService->getCharacteristic(OnOffCharacteristicUUID);

    Serial.printf("Characteristic readable: %s\n", boolToString(onOffCharacteristic->canRead()));
    Serial.printf("Characteristic writable: %s\n", boolToString(onOffCharacteristic->canWrite()));
    Serial.printf("Characteristic writable (without response): %s\n", boolToString(onOffCharacteristic->canWrite()));
    Serial.printf("Characteristic supports notifications: %s\n", boolToString(onOffCharacteristic->canNotify()));
    onOffCharacteristic->subscribe(true, onOffStateNotified, true);

    Serial.printf("Characteristic value: %s\n", boolToString(onOffCharacteristic->readValue<bool>()));
}

void onOffStateNotified(BLERemoteCharacteristic* pBLERemoteCharacteristic, uint8_t* pData, size_t length, bool isNotify)
{
    Serial.printf("Light switch has been physically pressed. State: %s\n", boolToString(pData[0]));
    digitalWrite(LED_PIN, pData[0]);
}

unsigned long last = 0;
bool switchState = false;

void loop() 
{
    if(millis() - last >= 5000)
    {
        last = millis();
        onOffCharacteristic->writeValue(switchState = !switchState, true);
    }
}
```
This is the serial output of the program: https://pastebin.com/5EykFiP9 (debug level is set to 5)
I pressed the switch a few times while the program was running to show that notifications work. After a while the esp gets disconnected. The esp reports that it isn't bonded, and I am fairly certain that is the issue. How do I get the esp to bond with the light switch? 
The esp I am using is a DOIT ESP32 DEVKIT V1, if it matters

**Comment by PORTB** [comment]
I removed it, but I'm still getting the same result https://pastebin.com/u3MD4fiV

**Comment by h2zero** [comment]
This is quite strange, when you read the characteristic it looks like it's not starting the pairing process. I don't know how this could happen and the logs don't show anything. I'll have to try to reproduce this.

**Comment by h2zero** [comment]
Great, I'm glad you found the issue!

The return code means this:
0x0213 | 0x13 | BLE_ERR_REM_USER_CONN_TERM | Remote User Terminated Connection
-- | -- | -- | --

You can look these up here https://mynewt.apache.org/latest/network/ble_hs/ble_hs_return_codes.html
converting the decimal value to hex first of course, 531 = 0x213 .
