### ISSUE TITLE
Simply write a string

### ISSUE THREAD

**Issue by morgan-wild** [h2zero/NimBLE-Arduino#306]
Hi everybody.

I'm facing something strange trying to write a simple Arduino String into a characteristic.

With the 'official' library, I used this method and it worked:

```
        String message = "Value is " + String(_value);

        _pCharacteristicRead->setValue(message.c_str());  // Value is 4
        _pCharacteristicRead->notify();     // To fire and forget.
```

But with NimBLE, I got some strange character to the other side (A web app).

I tried with and without setFormat(NimBLE2904::FORMAT_UTF8) on this characterisic, but no change.

I also tried something permitted whith this library:

```
         String message = "Value is " + String(_value);

        _pCharacteristicRead->setValue(message); // -> ���?
        _pCharacteristicRead->notify();     // To fire and forget.
```

But I have the same result.

Strange thing, if I use that, it works!

```
        _pCharacteristicRead->setValue("Value is "); // -> Value is 
        _pCharacteristicRead->notify();     // To fire and forget.
```

But with 

```
        _pCharacteristicRead->setValue("Value is " + String(_value)); -> // -> \��?
        _pCharacteristicRead->notify();     // To fire and forget.
```

It is down again.

Any idea?

Regards.

**Comment by h2zero** [comment]
Closing this as resolved in master branch with `NimBLEAttValue` class.

**Comment by Diaver** [comment]
Hey @h2zero  !
Platformio: h2zero/NimBLE-Arduino@^1.4.1
Issue still here :(
Have to use workaround with std::string(command.c_str())

**Comment by h2zero** [comment]
Can you share the code snippet that doesn't work as expected?

**Comment by Diaver** [comment]
> Can you share the code snippet that doesn't work as expected?

Thanks for reply! There is no really what to share except that with your library I need initialize std::string:
```c
this->pCharacteristic->setValue(std::string(subCommand.c_str()));
``` 
vs default:
```c
this->pCharacteristic->setValue(subCommand.c_str());
```

Full source code would looks like that:
```c
void BtService::SendCommand(String command)
{
  Serial.println("BT sending new command:" + command);     
  
  int start = 0;

  while (start < command.length())
  {
    int end = start + 20 > command.length()
      ? command.length()
      : start + 20;

    String subCommand = command.substring(start, end);

    //stock library
    this->pCharacteristic->setValue(subCommand.c_str());

    //NimBLEDevice library
    this->pCharacteristic->setValue(std::string(subCommand.c_str()));

    this->pCharacteristic->notify();
    start += 20;
  }
  Serial.println("BT command sent" + command);     
}
```
