### ISSUE TITLE
Scan Result differs on Wroom 32/D

### ISSUE THREAD

**Issue by ArcadeD3vil** [h2zero/NimBLE-Arduino#307]
Hey mates, today i detected the following error:
while scanning with a Wroom32D i get the advertised device (TI CC2541) listed for what im looking for.
But when i use another device with a Wroom32 chip, without the D at the end, the scanresult is the same, but the CC2541 Device is not listed.  What could be the reason for this behavior?

**Comment by h2zero** [comment]
Closing as this is not a library issue.
