### ISSUE TITLE
Safely enabling and disabling bluetooth radio on demand

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [h2zero/NimBLE-Arduino#312]
Hi. Forgive me because I feel like I've asked this question before some time ago, but I can't remember the answer and I can't find it anywhere.

I would like to enable and disable the radio through software. My device is drawing too much power and based on my initial findings about .10amps of that off of my USB port is going to the bluetooth

I want to have a connect button (momentary SPST) that I use to initiate a bluetooth connection, and then if it's not finding a connecting host I want it to timeout after say 30 seconds (it doesn't really matter, as long as you get the idea)

Here's my code to kick everything off.

```
const char* szn = "Test Device";
NimBLEDevice::init(szn);
NimBLEDevice::setPower(ESP_PWR_LVL_P9);
NimBLEDevice::setSecurityAuth(BLE_SM_PAIR_AUTHREQ_SC);
m_pserver = NimBLEDevice::createServer();
m_pserver->setCallbacks(&m_server_callbacks,false);
m_pserver->advertiseOnDisconnect(false);
m_pservice = m_pserver->createService(service_id);
NimBLECharacteristic *pSessionCharacteristic = m_pservice->createCharacteristic(
    session_char_id,
    NIMBLE_PROPERTY::READ |
    NIMBLE_PROPERTY::WRITE |
    NIMBLE_PROPERTY::NOTIFY);
pSessionCharacteristic->setCallbacks(&m_char_callbacks);
m_pservice->start();
...
NimBLEAdvertising *pAdvertising = NimBLEDevice::getAdvertising();
pAdvertising->addServiceUUID(m_pservice->getUUID());
pAdvertising->setScanResponse(true);
```
So my question is, basically first, can I just call
```
NimBLEDevice::deinit(true);
```
or whatever, and then run the initialization code again when I want to kick things off again?

Will that do what I want, and is it safe? If not, then how do I go about it?

Thanks in advance!

**Comment by h2zero** [comment]
Hi @codewitch-honey-crisis, what you propose would be correct to shut down the BLE stack and radio. 

Alternatively though is you could just disconnect any clients and not advertise until a later time. The radio should not be in use without any active connection or advertising/ scanning.
