### ISSUE TITLE
Compilation Error with freeRTOS

### ISSUE THREAD

**Issue by gktval** [h2zero/NimBLE-Arduino#313]
Hi, I am attempting to compile the library using the Arduino Nano 33 BLE. When compiling, I am getting an error that it cannot find FreeRTOS.h. I installed FreeRTOS through the library manager, but the error remains. Do I need to place freeRTOS elsewhere or should it be automatically installed when NimBLE is installed? Thanks

![image](https://user-images.githubusercontent.com/7605046/143325695-40dc9bf5-c6c3-4fbb-887f-d6eaca1f75d1.png)

**Comment by h2zero** [comment]
Hi @gktval, sorry but at the moment this library only supports the esp32 arduino core. 

I have a nearly ready core for arm processors that I started months ago and have not had time to complete it yet but hope to soon.

It will be announced here when its available.

**Comment by gktval** [comment]
Ah. That's good to hear.  I will close this then.

**Comment by h2zero** [comment]
@gktval Since you asked about this I thought I'd let you know that the core is now available if you're interested. Please see #314
