### ISSUE TITLE
Get data from server

### ISSUE THREAD

**Issue by VictorMulet** [h2zero/NimBLE-Arduino#319]
Hello, I'm trying to communicate with a watch from BLE but I can't access to Hearth Rate data. Have you already done this and what can be the issue to do this ? Actually I'm with a fitbit watch but after I'll go to the SB brand.
I'm able to get all the services allowed as a client but can't reach to data more private...
Thanks for your time

**Comment by h2zero** [comment]
I'm not familiar with reading from a fitbit but I suspect you may need to pair/bond with it to read the data.

**Comment by VictorMulet** [comment]
I've done this but we can't access to all data through nRF Connect and it's the same with the ESP32. Did you have any idea ?

**Comment by h2zero** [comment]
Unfortunately I can't offer much help for this as I don't have enough information about the device. It could be that it only sends the data by notification so you would need to subscribe to those on the characteristic. Only a guess though.

**Comment by VictorMulet** [comment]
Thank you for the time you've spend answering my question and I'll try to use your thoughts.
