### ISSUE TITLE
Not work in ESP-WROOM-32

### ISSUE THREAD

**Issue by hdpklm** [h2zero/NimBLE-Arduino#320]
Hello

Server is ESP32 (WROOM, ESP32-D2WD)
Client Mobile application: Cordova + plugin [cordova-plugin-ble-central]
I have a problem when I upload the Server code to WROOM and connect from client its connect normaly, but it can't subscrive to notification.
but when I use the ESP32-D2WD as server with the same code, eveny think is work ok

**Comment by h2zero** [comment]
Hi @hdpklm this is an odd problem, there are some issued with certain esp32 modules but that mostly is related to receiving sensitivity. Can you share a code snippet that I can try to reproduce with? Also any other relevant details would be appreciated.

**Comment by hdpklm** [comment]
Hello @h2zero  

I upload the code and  a text file to build the same envierment
https://github.com/hdpklm/test-nim-ble

you need a ESP32-D2WD to test it, or you can test with several uC

thank you

**Comment by h2zero** [comment]
Thanks I'll have a look this weekend when I get some time.

**Comment by h2zero** [comment]
Had at look at your code, I see you are enabling both notification and indications. I suggest trying to on enable one of those and see what happens.
