### ISSUE TITLE
Getting guru error while using setvalue in loop 

### ISSUE THREAD

**Issue by yashram96** [h2zero/NimBLE-Arduino#322]
i want to update status of lamp. so using setvalue in a loop. But i am getting an error 
"Guru Meditation Error: Core 1 panic'ed (StoreProhibited). Exception was unhandled" please help me

**Comment by h2zero** [comment]
I can help you with this but I need more info. Can you share your code?

**Comment by peetjh** [comment]
I am having the same issue, below is my code.
`#include <NimBLEDevice.h>

NimBLECharacteristic* pCharacteristic = NULL;
#define BLEDescriptorCallbacks  NimBLEDescriptorCallbacks
bool deviceConnected = false;
bool oldDeviceConnected = false;
unsigned long startTime = 0;
int ledPin = 2;
int ledState = LOW;
int btCount = 0;

class ServerCallbacks: public NimBLEServerCallbacks {
    void onConnect(NimBLEServer* pServer) {
      deviceConnected = true;
      Serial.println("DeviceConnected");
    }

    void onDisconnect(NimBLEServer* pServer) {
      deviceConnected = false;
      Serial.println("DeviceDisconnected");
    }
};
class DescriptorCallbacks : public NimBLEDescriptorCallbacks {
    void onWrite(NimBLEDescriptor* pDescriptor) {
        std::string dscVal((char*)pDescriptor->getValue(), pDescriptor->getLength());
    }
    void onRead(NimBLEDescriptor* pDescriptor) {
        //Serial.print(pDescriptor->getUUID().toString().c_str());
        //Serial.println(" Descriptor read");
    }    
};

void setup()
{
    Serial.begin(115200);
    pinMode(2, OUTPUT);   //NEEDED FOR BOOT AND LED FLASHING
    digitalWrite(2, LOW);   //NEEDED FOR BOOT
    NimBLEDevice::init("ESP32_TEST");
    
    NimBLEServer *pServer = NimBLEDevice::createServer();
    NimBLEService *pService = pServer->createService("331F1570-8A00-9A28-CBE1-E1D4212D53EB");
    NimBLECharacteristic *pCharacteristic = pService->createCharacteristic("331F1571-8A00-9A28-CBE1-E1D4212D53EB",
             NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY);
    NimBLECharacteristic *pCharacteristic1 = pService->createCharacteristic("331F1572-8A00-9A28-CBE1-E1D4212D53EB",
             NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::WRITE_NR);
    
    pService->start();
    
    pCharacteristic->setValue("OOO");
    NimBLEAdvertising *pAdvertising = NimBLEDevice::getAdvertising();
    pAdvertising->addServiceUUID("331F1570-8A00-9A28-CBE1-E1D4212D53EB"); 
    pAdvertising->start(); 
}
void loop()
{
      if (deviceConnected == false){
      unsigned long loopTime = millis() - startTime; //Calculate loop time
      if (loopTime >= 2000) //Check that the time is 1 second
      {startTime = millis();
        if(ledState == LOW){
          ledState = HIGH;
        }
        else{
          ledState = LOW;
        }
        digitalWrite(ledPin, ledState);
        Serial.println(ledState);
        pCharacteristic->setValue("XXX");
      }
        btCount = 0; 
      }
      else{
        if (btCount == 0){
        ledState = HIGH;
        digitalWrite(ledPin, ledState);
        Serial.println(ledState);
        btCount = 1;
      } 
    }
}`

**Comment by h2zero** [comment]
Your issue is not initializing the global:
 `NimBLECharacteristic* pCharacteristic = NULL;` 

and then using it in the loop:
`pCharacteristic->setValue("XXX");`

Changing this:
```
NimBLECharacteristic *pCharacteristic = pService->createCharacteristic("331F1571-8A00-9A28-CBE1-E1D4212D53EB",
             NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY);
```

To:
```
pCharacteristic = pService->createCharacteristic("331F1571-8A00-9A28-CBE1-E1D4212D53EB",
             NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY);
```

Will solve your problem.

**Comment by peetjh** [comment]
Thanks, that fixed it.

**Comment by h2zero** [comment]
Closing as resolved.
