### ISSUE TITLE
Client memory corruption

### ISSUE THREAD

**Issue by aovestdipaperino** [h2zero/NimBLE-Arduino#344]
I don't have a clue yet on why this happens, but very often the client side handle value of a characteristic gets corrupted.
This is the flow:
scan
connect
get service
get characteristic
write value

I added a debug statement in NimBLEClient.
Half of the times, after reboot, the handle value of the characteristic gets corrupted, so notifications don't reach the app.

I plan to add more logging statements trying to catch what causes this corruption, but any pointers help here.

**Comment by h2zero** [comment]
>Half of the times, after reboot, the handle value of the characteristic gets corrupted, so notifications don't reach the app.

I'm not sure I understand, what are you rebooting when this happens? Do you have any logs of this?

**Comment by h2zero** [comment]
Closing as stale. Please reopen if still having this issue.
