### ISSUE TITLE
Memory leak in continuous scan

### ISSUE THREAD

**Issue by rovale** [h2zero/NimBLE-Arduino#361]
Hello!

It looks like there might be a memory leak in the continuous scan. I did a minor change in the callback to make this show:

``` cpp
class MyAdvertisedDeviceCallbacks : public NimBLEAdvertisedDeviceCallbacks
{
    void onResult(NimBLEAdvertisedDevice *advertisedDevice)
    {
        Serial.printf("%i - %i \n", ESP.getFreeHeap(), advertisedDevice->toString().length());
    }
};
```

The output looks as follows, this is just a couple of minutes. Over time the memory will not be released.
```
265792 - 113
265792 - 95
265792 - 163
265792 - 113
265792 - 95
265792 - 163
265792 - 163
265792 - 95
265792 - 113
265792 - 95
265792 - 113
265792 - 163
265792 - 95
265792 - 113
265792 - 163
265792 - 113
265792 - 95
265792 - 163
265792 - 87
265660 - 67
265660 - 95
265660 - 113
265660 - 163
265660 - 113
265660 - 95
265660 - 113
265660 - 163
265660 - 95
265660 - 113
265660 - 163
265520 - 88
265524 - 95
265524 - 113
265524 - 163
265524 - 67
265524 - 95
265524 - 113
265524 - 163
265396 - 163
265396 - 113
265396 - 67
265524 - 95 
265524 - 113 
265524 - 163 
265524 - 95 
265524 - 113 
265524 - 163 
265396 - 113 
265396 - 163
```

I am using a Wemos Lolin D32 with PlatformIO Espressif 32 3.5.0, and this library, version 1.3.7.

Is there something I can try to possibly release the memory?

**Comment by h2zero** [comment]
Some memory is consumed by the vector, depending on the number of devices for which the scan is waiting for a scan response. This will increase the size of the vector up to a certain point at the max devices encountered that a response is being waited from. Since the vector never actually frees the memory allocated, I believe this is what you're observing in the logs.

You can see in this section that it settles out and some memory is recovered:
```
265524 - 95
265524 - 113
265524 - 163
265396 - 163
265396 - 113
265396 - 67
265524 - 95 
265524 - 113 
265524 - 163 
265524 - 95 
265524 - 113 
265524 - 163 
265396 - 113 
265396 - 163
```

**Comment by rovale** [comment]
> But this might be because i used `pBLEScan->setMaxScanResults(0);` -No memory is used to store the scan results.

I think you mean `pBLEScan->setMaxResults(0);` but that is already in the example.

**Comment by sivar2311** [comment]
> I think you mean pBLEScan->setMaxResults(0); but that is already in the example.

Yes correct - sorry for the typo.

@h2zero Might `clearResults()` help here?
It clears the advertisedDeviceVector.

**Comment by rovale** [comment]
I just ask this question because I clearly see a memory leak in my application, and I tried to come up with an easy repro. I will let it run for a longer time to see if it will recover the memory in this example.

**Comment by sivar2311** [comment]
I have found the difference with the code I use:
I use `pBLEScan->setActiveScan(false)` (because I am only interested in the manufacturer data).
Et voila: the free heap remains (almost) constant.

**Comment by h2zero** [comment]
That cache is in the controller, when it reaches the limit specified it clears that data itself.

**Comment by rovale** [comment]
Yes, it looks like that was what I was observing.

If I understand correctly, the default type is CONFIG_BTDM_SCAN_DUPL_TYPE with a cache size of 20 so that is what you get when you comment it out. The minimum cache size is 10.

**Comment by h2zero** [comment]
Yes, you're interpreting that correctly.

**Comment by h2zero** [comment]
You could try using the white list filter, add the address here (be sure you know the address type of the device first):
https://github.com/h2zero/NimBLE-Arduino/blob/c155fa80fbb0f2df4e4c68ca1b44c1a2de30cfdb/src/NimBLEDevice.cpp#L617

Then set the scan filter policy:
https://github.com/h2zero/NimBLE-Arduino/blob/c155fa80fbb0f2df4e4c68ca1b44c1a2de30cfdb/src/NimBLEScan.cpp#L206

**Comment by rovale** [comment]
Yes, this is perfect, thank you!

**Comment by rovale** [comment]
Hello @h2zero, can you please help me out? The code below works perfectly fine to get data advertisement data from a whitelisted SwitchBot meter, but now I try to send data using an ESP32 and I just cannot get through the whitelist filter. I must be missing something obvious...

The client
```
#include <Arduino.h>
#include "NimBLEDevice.h"

class Advertisement : public NimBLEAdvertisedDeviceCallbacks {
  void onResult(NimBLEAdvertisedDevice *advertisedDevice) {
      NimBLEAddress advertisedAddress = advertisedDevice->getAddress();
      auto serviceData = advertisedDevice->getServiceData(0).c_str();
      Serial.printf("Advertisement from %s - %s\n", advertisedAddress.toString().c_str(), serviceData);
  }
};

void setup() {
    Serial.begin(115200);
    while (!Serial && !Serial.available()) {
    }

    NimBLEDevice::setScanFilterMode(CONFIG_BTDM_SCAN_DUPL_TYPE_DEVICE);
    NimBLEDevice::setScanDuplicateCacheSize(10);
    NimBLEDevice::init("BleClient");

    NimBLEDevice::whiteListAdd(NimBLEAddress("fe:21:1e:ca:35:d9", BLE_ADDR_RANDOM));
    NimBLEDevice::whiteListAdd(NimBLEAddress("30:ae:a4:03:91:9a", BLE_ADDR_RANDOM));

    NimBLEScan *pBLEScan = NimBLEDevice::getScan();
    
    // When I comment out this line I do get data from 30:ae:a4:03:91:9a
    pBLEScan->setFilterPolicy(BLE_HCI_SCAN_FILT_USE_WL);

    pBLEScan->setAdvertisedDeviceCallbacks(new Advertisement(), false);
    pBLEScan->setActiveScan(true); // Set active scanning, this will get more data from the advertiser.
    pBLEScan->setInterval(97);     // How often the scan occurs / switches channels; in milliseconds,
    pBLEScan->setWindow(37);       // How long to scan during the interval; in milliseconds.
    pBLEScan->setMaxResults(0);    // do not store the scan results, use callback only.  
}

void loop() {
    // Starting the scan. If an error occurs that stops the scan, it will be restarted here.
    NimBLEScan *pBLEScan = NimBLEDevice::getScan();
    if (!pBLEScan->isScanning()) {
        Serial.printf("(Re)starting the BLE scan\n");
        // Start scan with: duration = 0 seconds(forever), no scan end callback, not a continuation of a previous scan.
        pBLEScan->start(0, nullptr, false);
    }
}

```

The meter
```
#include <Arduino.h>
/** NimBLE_Service_Data_Advertiser Demo:
 *
 *  Simple demo of advertising service data that changes every 5 seconds
 *
 *  Created: on February 7 2021
 *      Author: H2zero
 * 
*/

#include "NimBLEDevice.h"

#define SERVICE_UUID "4fafc201-1fb5-459e-8fcc-c5c9c331914b"

static NimBLEUUID dataUuid(SERVICE_UUID);
static NimBLEAdvertising *pAdvertising = NimBLEDevice::getAdvertising();
static uint32_t count = 0;

void setup() {
  Serial.begin(115200);
  Serial.println("Starting BLE work!");
  
  NimBLEDevice::init("svc data");
}

void loop() {
  pAdvertising->stop();
  pAdvertising->setScanResponse(true);  

  pAdvertising->setServiceData(dataUuid, std::string((char*)&count, sizeof(count)));
  pAdvertising->start();
  
  Serial.printf("Advertising count = %d\n", count);
  count++;
  delay(5000);
}
```
