### ISSUE TITLE
Unable to specify channel algorithm #2

### ISSUE THREAD

**Issue by kiowadriver** [h2zero/NimBLE-Arduino#363]
How would one specify channel algorithm #2 in the server ADV_IND?

I can't seem to find it anywhere in the interface, documentation, or examples. 

Example please?

**Comment by h2zero** [comment]
I'm not sure what you mean by "channel algorithm #2". Could you provide more details of what you would like to do?

**Comment by kiowadriver** [comment]
The peripheral advertisement can advertise ch algorithm #1 or #2.  By
default it is #1.

Description:
https://software-dl.ti.com/lprf/simplelink_cc2640r2_sdk/1.35.00.33/exports/docs/ble5stack/ble_user_guide/html/ble-stack/channel-selection-algorithm-number-two.html

How would I pass the following parameter as part of my ADV configuration?

*#include <esp_gap_ble_api.h>*

ESP_GAP_BLE_CHANNEL_SELETE_ALGORITHM_EVT.

Public Members
uint16_t conn_handle
<https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gap_ble.html#_CPPv4N22esp_ble_gap_cb_param_t25ble_channel_sel_alg_param11conn_handleE>

connection handle
uint8_t channel_sel_alg
<https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gap_ble.html#_CPPv4N22esp_ble_gap_cb_param_t25ble_channel_sel_alg_param15channel_sel_algE>

channel selection algorithm

**Comment by h2zero** [comment]
Thanks, now I understand. I believe this cannot be set manually, it should be set by the controller if supported, which is closed source. Also I think this will only work with BLE 5.0 supported devices (esp32c3/s3).

**Comment by kiowadriver** [comment]
Thanks for the reply.

I am running a Lolin_D32_Pro ESP32-WROVER-E.  It looks like it
supports: Version
4.2 BR/EDR and BLE specifications.

**Comment by h2zero** [comment]
Closing this as it's not applicable to this repo at this time.

**Comment by kiowadriver** [comment]
We with the new S3 supporting BLE 5.x. will this now be related to this
repo?

**Comment by h2zero** [comment]
NimBLE only provides this as a compile time config for the controller, which is not used by the current ESP32 devices. It is likely already enabled in espressif's controller so there is not much to do for this. The link in the doc's is just describing a callback event in the bluedroid code that tells you about the CSA for the connection.
