### ISSUE TITLE
Nimble-arduino supports coded phy in connectable mode 

### ISSUE THREAD

**Issue by iamcalledusman** [h2zero/NimBLE-Arduino#374]
Hi

My question is that Nimble-Arduino supports **coded PHY in connectable mode** or not? If yes can you please help me to point out which files need to change?

Thanks, And Regards,

**Comment by h2zero** [comment]
Support for that is currently in progress. I should have an update soon.

**Comment by iamcalledusman** [comment]
Hi @h2zero 

thank you! i will wait for it
