### ISSUE TITLE
pBLEClient->getCharacteristic(handle) returns NullPtr

### ISSUE THREAD

**Issue by miksumin** [h2zero/NimBLE-Arduino#378]
Hello, I found that using pBLEClient->getCharacteristic(handle) right after successful connection returns NullPtr.
After debugging the issue in library version 1.3.6 I found that discovering of Services and Characteristics are missing in the mentioned function.
So I suggest to add it in your code:

NimBLERemoteCharacteristic* NimBLEClient::getCharacteristic(const uint16_t handle)
{
	
	getServices(true);			// added
	
	NimBLERemoteService *pService = nullptr;
    for(auto it = m_servicesVector.begin(); it != m_servicesVector.end(); ++it) {
      if ((*it)->getStartHandle() <= handle && handle <= (*it)->getEndHandle()) {
          pService = *it;
          break;
      }
    }

    if (pService != nullptr) {

	pService->getCharacteristics(true);		// added

        for (auto it = pService->begin(); it != pService->end(); ++it) {
            if ((*it)->getHandle() == handle) {
                return *it;
            }
        }
    }

    return nullptr;
}

**Comment by h2zero** [comment]
Thank you for bringing this up. I guess it was assumed that the application would have retrieved the attribute database before using this function. Adding a check and retrieving the database if necessary is certainly a good idea in this case.

**Comment by h2zero** [comment]
I have a question, what is your use case for this? I remember it was added when someone wanted to probe some devices seen on a scanner but I don't see much other use.

**Comment by miksumin** [comment]
I am discovering communication with Mi Flora device without any documentation for it protocol just looking for someone else's code where they use handles. But as for now I found applications that makes a full discover of services/characteristics of my device.

**Comment by h2zero** [comment]
I've decided this should not be changed. The application should retrieve the database with `discoverAttributes` or any other method before using this.
