### ISSUE TITLE
How to decrease the time of upload?

### ISSUE THREAD

**Issue by sa7brina** [h2zero/NimBLE-Arduino#399]
Hi,
I'm using the nimBle Library for Upload the ESP32's firmware.
My smartphone application send packets of 128 bytes, but I have to wait 60ms between each shipment otherwise an error occurs :
E (230606) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
I try to increase the ACL_BUF_COUNT, no effect.
How I can decrease the time between two shipment? ideally, I would like to go down to about 10ms.

**Comment by h2zero** [comment]
Hello, you can request different connection parameters to reduce this down to a minimum of 7.5ms.
`pServer->updateConnParams(conn_handle, 6, 6, 0, 200);`
