### ISSUE TITLE
Does NimBLE do a CRC check when receiving a frame?

### ISSUE THREAD

**Issue by Bascy** [h2zero/NimBLE-Arduino#401]
As i understand it all BLE frames contain a 3 byte CRC at the end, calculated over the header, address and payload parts of the frame.

Does NimBLE check the CRC after receiving a frame?

I do find some CRC related stuff in the source code but not much on actual implementation, but maybe I'm looking in the wrong direction....

**Comment by h2zero** [comment]
Yes CRC's are calculated, if I recall correctly it is done by the closed source controller binary, not the host.
