### ISSUE TITLE
Multiple characteristics limitation

### ISSUE THREAD

**Issue by Zparq** [h2zero/NimBLE-Arduino#408]
Hi,

Trying to use multiple characteristics but we have an issue when the characteristics are more than 7. If increasing the number of characteristics and activating notification on them, some characteristics stops updating their values. Keeping it below 7 and everything seems ok. Slowing down the pace has no effect nor anything else we tried. The only remaining possible explenation is that there is a limitation in the code somehow around 7 notifying characteristics.  If I look at the ESP BLE reference code there is talk about a parameter when creating a service, to increase numHandles=15. This parameter is not present in NimBLE. How and where is this set in NimBLE?

**Comment by Zparq** [comment]
As an update. We thought we could issue a warkaround using two services, splitting characteristics on them. This also however does not work. No matter what the number of characteristics is limited to 7 even when there is 4 on one service and 3 on another.

**Comment by h2zero** [comment]
There is no handle limit in NimBLE which is why that parameter was removed. What I suspect may be happening is you could be running out of buffers, do you see any errors in the logs?

**Comment by h2zero** [comment]
Closing as stale. Please reopen if still and issue.

**Comment by 46cv8** [comment]
If you THINK you are running into this issue and increasing your buffer size doesn't help I recommend also clearing your bluetooth cache for the device that is failing. A bad cache turned out to be my issue.
