### ISSUE TITLE
Set Characteristic handle problem

### ISSUE THREAD

**Issue by mobier** [h2zero/NimBLE-Arduino#415]
Service UUID:4fafc201-1fb5-459e-8fcc-c5c9c331914b handle:0x000a
Characteristic 1,handle:0x000c
Characteristic 2,handle:0x000e

I would like to ask if it is possible to set or modify the handle of Characteristic 2 from 0x0e to 0x0f.
Previously studied the code of the arduino-esp32 project `libraries/ble/src/blecharacteristic.cpp:603 setHandle (uint16_t handle)` is a private setting method, but the handle cannot be set after trying to call.

**Comment by h2zero** [comment]
The NimBLE stack does not allow for setting handles manually. The private method is private because the value is set from the value provided by the stack and if altered it would break the functionality.
