### ISSUE TITLE
Send data to a specific device in the characteristic

### ISSUE THREAD

**Issue by roysG** [h2zero/NimBLE-Arduino#425]
I am trying yo send sensitive data to specific device id in the characteristic.
But as i test it, i can see the sensitive data also from others devices that connected to the same service/characteristic.

Is there any option to isolated the transferd data just for the specific device?

**Comment by h2zero** [comment]
If other devices are connected and all writing to the same characteristic then there is nothing from the client side that could be done. However on the server side it may be able to save the written data and the address of the client and store it separately in from the onWrite callback.

**Comment by roysG** [comment]
Ok, in case i know the adreessId of the device. do i have the ability to send just him messages?

**Comment by h2zero** [comment]
Sorry, not sure if I follow what you're asking. I'm guessing the esp32 is acting as a server and you want to notify a specific client only? This could be done but the capability is not implemented in the library at this time.

**Comment by JulienLecoq** [comment]
Hello guys, I'm also looking for this functionality. Notifying a single client will allow to create more easily request/response pattern. It would be of great benefit. :)

**Comment by h2zero** [comment]
This should be possible without too much trouble, I'll add this as a future feature.

**Comment by JulienLecoq** [comment]
Cool ! :)

**Comment by h2zero** [comment]
This has been added in the master branch.
