### ISSUE TITLE
How to stop a service?

### ISSUE THREAD

**Issue by AndrewMagpie** [h2zero/NimBLE-Arduino#433]
There is a `bool NimBLEService::start()`
But no `bool NimBLEService::stop()`, unlike the nkolban version.

How does one stop a service?

**Comment by h2zero** [comment]
The NimBLE stack does not support stopping a service the way the bluedroid stack does. Instead it can "hide" it or delete it completely. For this to work advertising must be stopped first.

The function to do this is in NimBLEServer:
`void NimBLEServer::removeService(NimBLEService* service, bool deleteSvc = false);`

**Comment by sdetweil** [comment]
@h2zero  except this appears not to work..
