### ISSUE TITLE
only changes BLE MAC address

### ISSUE THREAD

**Issue by mobier** [h2zero/NimBLE-Arduino#444]
Hello, the official `esp_base_mac_addr_set` api can be used to modify the wifi/bleMAC address of esp32, but there is a problem that if you want to set the MAC to "11:xx:xx:xx:xx:xx", This address is a multicast MAC address in WiFi, the program reports an error `E (14) system_api: Base MAC must be a unicast MAC` (least significant bit of *first byte must be zero*), I would like to ask if there is a way to only modify the BLE mac address

**Comment by h2zero** [comment]
Hello @mobier please see #430 as the solution for now is discussed there. I will make an update in the near future to make this easier.
