### ISSUE TITLE
minInterval less then 6 possible?

### ISSUE THREAD

**Issue by marchingband** [h2zero/NimBLE-Arduino#466]
Hello.
Amazing library thank you!
I am making a BLE MIDI device, and this use case requires low latency.
I noticed there is a check in `NimBLEUtils.cpp` preventing us from setting `minInterval` any lower then `6` (~9ms).
I am hoping to achieve closer to 1 ms :(
Is there any way to achieve lower latency in receiving a notify event?
thanks!

**Comment by h2zero** [comment]
The units for this setting are 1.25ms, a setting of 6 = 7.5ms which is the minimum allowed by bluetooth specification. There is no way to reduce this as it is a hard limit.

**Comment by marchingband** [comment]
Oof ok thank you!
