### ISSUE TITLE
Can't get descriptor of a service for notifications

### ISSUE THREAD

**Issue by Jimbo210** [h2zero/NimBLE-Arduino#477]
Hi, opening this issue as i wasn't able to find any solution by myself or through the web.
I'm kind of new to the world of ble and esp32, so I might be missing some basics. My final goal is to move a code I got running on pc to the esp32, but since I used different libraries I still have to aclimatize to the new set of functions.

I'm currently stuck at trying to get the descriptor of the primary service, to subsequently send some bytes and subscribe for notification, as this is what I was doing from pc: 
- getting all descriptors; 
- finding the one with the specific Uuid("00002902");
- sending the bytes ("x01, x00") to subscribe for notifications;

From my understanding the hierarchy of the library is: Client -> Service -> Characterstic -> Descriptor and each step has it's own set of functions, hence I'm not able to call getDescriptors() from a service.

(As a spot of context I'll leave the screenshot of nRF Connect to show what I'm trying to see/get with the esp32).

![Screenshot_nRF](https://user-images.githubusercontent.com/73823340/203146892-63b278a9-190b-4e95-b75b-1e41b5521602.png)
 
I can subscribe and write to the two characteristic in question, but canNotify() returns false...
Am I missing something or is there other way of subscribing for notifications?

Code:

<

      #include <NimBLEDevice.h>
    
      static NimBLEClient* pClient;
    
      NimBLEAddress devAddress("ce:1a:74:6b:2d:bc");
      NimBLEUUID serviceUuid("14839ac4-7d7e-415c-9a42-167340cf2339");
      NimBLEUUID charUuid1("8b00ace7-eb0b-49b0-bbe9-9aee0a26e1a3");
      NimBLEUUID charUuid2("0734594a-a8e7-4b1a-a6b1-cd5243059a57");
      //NimBLEUUID descUuid2("00002902");
    
      std::vector<uint8_t> wrBv = { 0xAA, 0x17, 0xE8, 0x00, 0x00, 0x00, 0x00, 0x1B };
      std::vector<uint8_t> subBv= { 0x01, 0x00 };
    
    
    void notificationCallBack(NimBLERemoteCharacteristic* pRemoteCharacteristic, uint8_t* pData, size_t length, bool isNotify){ 
        Serial.println("Received Notification");
    }
    
    void setup() {
      Serial.begin(115200);
    
      Serial.println("Starting NimBLE Client");
      NimBLEDevice::init("");
      pClient = NimBLEDevice::createClient(NimBLEAddress("ce:1a:74:6b:2d:bc", 1));
      Serial.println("New client created");
    
      if(pClient->connect()) {
    
            Serial.println("Connected to device.");
    
            NimBLERemoteService* pService = pClient->getService(serviceUuid);
    
            NimBLERemoteCharacteristic* pCharacteristic1 = pService->getCharacteristic(charUuid1);
            
            if(pCharacteristic1->subscribe(true, notificationCallBack, true)){
              Serial.println("Subscribed");
            }
    
            if(pCharacteristic1->canNotify()){
              Serial.println("Can Notify");
            }
    
            if(pCharacteristic1->writeValue(wrBv)){
              Serial.println("Wrote");
            }
      }
    }
    
    void loop() {
    
    }
>

Thank in advance for the replies.
Best Regards.

**Comment by h2zero** [comment]
As you can see in the nRFConnect screenshot, the characteristic `NimBLEUUID charUuid1("8b00ace7-eb0b-49b0-bbe9-9aee0a26e1a3");` does not have notification capabilities.

You are attempting to subscribe to it here:
```

        NimBLERemoteCharacteristic* pCharacteristic1 = pService->getCharacteristic(charUuid1);
        
        if(pCharacteristic1->subscribe(true, notificationCallBack, true)){
          Serial.println("Subscribed");
        }

        if(pCharacteristic1->canNotify()){
          Serial.println("Can Notify");
        }
``` 
`canNotify()` should return false here for this characteristic.

I believe you meant to use the `charUuid2` here, which as shown, has notification property enabled.

**Comment by Jimbo210** [comment]
First of all thanks for the reply and for making me check again.

<charUuid2> was in fact the one which I should have been subscribing to and I got everything working.

I'll point out some issues that I have found, even though I later realized I didn't actually need those functions results (but it might be helpful to someone or I could learn why they were there).

The descriptor which I was looking for (that I didn't need) was in deed "within"  <charUuid2>, but getting to it wasn't so easy:
 - pCharacteristic->getDescriptors(); returned a vector of size 0...
 - if I did the same thing after subscribing to the characteristic I get a vector of size 1 and could subsequently get to it's "features".
 - Couldn't get pCharacteristic->getDescritptor(UuidDescriptor) working tough...

Current (small) issue I have is I get two responses from the notificationCallBack function as if it's called twice:

Code: 
<

#include <NimBLEDevice.h>

  static NimBLEClient* pClient;

  NimBLEUUID serviceUuid("14839ac4-7d7e-415c-9a42-167340cf2339");
  NimBLEUUID charUuid1("8b00ace7-eb0b-49b0-bbe9-9aee0a26e1a3");
  NimBLEUUID charUuid2("0734594a-a8e7-4b1a-a6b1-cd5243059a57");

  std::vector<uint8_t> wrBv = { 0xAA, 0x17, 0xE8, 0x00, 0x00, 0x00, 0x00, 0x1B };

  NimBLERemoteCharacteristic* pChr1;

void whatToDo(NimBLERemoteCharacteristic* pRemoteCharacteristic, uint8_t pData[], size_t length, bool isNotify){
  Serial.println("Been here");
}

void setup() {

  Serial.begin(115200);

  Serial.println("Starting NimBLE Client");
  NimBLEDevice::init("");

  pClient = NimBLEDevice::createClient(NimBLEAddress("ce:1a:74:6b:2d:bc", 1));
  Serial.println("New client created");

  if(pClient->connect()) {
    Serial.println("Connected to device.");

    NimBLERemoteService* pService = pClient->getService(serviceUuid);

    NimBLERemoteCharacteristic* pCharacteristic1 = pService->getCharacteristic(charUuid1);
    NimBLERemoteCharacteristic* pCharacteristic2 = pService->getCharacteristic(charUuid2);

      if(pCharacteristic2->canNotify()){
        Serial.println("Can notify.");
        if(pCharacteristic2->subscribe(true, whatToDo, true)){
          Serial.println("subscibed.");
          pChr1 = pCharacteristic1;
        }
      }
  }
}

void loop() {
  pChr1->writeValue(wrBv);
  delay(3000);
}

>

Serial monitor:

<
19:09:36.505 -> Starting NimBLE Client
19:09:36.759 -> New client created
19:09:37.829 -> Connected to device.
19:09:38.545 -> Can Notify.
19:09:38.837 -> Subscribed
19:09:38.955 -> Been here
19:09:38.955 -> Been here
19:09:41.956 -> Been here
19:09:41.956 -> Been here
19:09:44.881 -> Been here
19:09:44.881 -> Been here
>

Thanks again for the reply and library

**Comment by h2zero** [comment]
> pCharacteristic2->getDescriptors(); returned a vector of size 0...

This occurs if you have not retrieved the descriptors yet.

> if I did the same thing after subscribing to the characteristic I get a vector of size 1 and could subsequently get to it's "features".

The call to subscribe will retrieve the descriptor info from the server so this is normal.

> Couldn't get pCharacteristic2->getDescritptor(UuidDescriptor) working though

What were you using for the UUID here? Not sure why you need to get the CCCD, could you explain a bit?

> Current (small) issue I have is I get two responses from the notificationCallBack function as if it's called twice:

That's strange, maybe the device sends the notification twice?
