### ISSUE TITLE
Repo description typo

### ISSUE THREAD

**Issue by pdcook** [h2zero/NimBLE-Arduino#485]
Super small typo. The description of the repo reads "Ardruino" instead of "Arduino". Thought I was going insane for a moment!

![image](https://user-images.githubusercontent.com/16090923/205747588-0ddc310f-6f49-4e9d-b238-96ebbc80929e.png)

**Comment by h2zero** [comment]
Lol thanks!

**Comment by h2zero** [comment]
Fixed now 😄
