### ISSUE TITLE
[Question] IO capabilites for pairing 

### ISSUE THREAD

**Issue by alberk8** [h2zero/NimBLE-Arduino#494]
Hi,
 I am trying out the NimBLE_Secure_Server example and it did work. 

What is the setting that is need for the BLEServer to present passkey Input dialog before ability to access the Services and Characteristic?  I am using nRF Connect on Android phone.   Thank you.

**Comment by h2zero** [comment]
The lines you'll want are:
```
NimBLEDevice::setSecurityIOCap(BLE_HS_IO_DISPLAY_ONLY); // use passkey
NimBLEDevice::setSecurityAuth(false, true, true);
```
