### ISSUE TITLE
Typo in include

### ISSUE THREAD

**Issue by juppees** [h2zero/NimBLE-Arduino#5]
I just took a quick look into your lib and got stuck due to a case sensitivity error.
In file
```NimBLE-Arduino/src/NimBLEDevice.h```, line 20 has to be written as
```#include "NimBLEScan.h"```
instead of
```#include "NimbleScan.h"```
to work in case sensitive operating systems like Linux.

Thanks,
Josef

**Comment by h2zero** [comment]
Omg lol, not sure how that happened, hopefully there isn’t any more instances like that. Thanks for reporting! I’ll fix it right away.
