### ISSUE TITLE
BLE whitelist filtering not completely working or gives error

### ISSUE THREAD

**Issue by I-Connect** [h2zero/NimBLE-Arduino#540]
Hi,

As there is a lot of BT traffic I wanted to use the whitelist, so I add all my devices (a Nuki smart lock and some different enocean switches and sensors) to the whitelist

If I use setFilterPolicy(1) it works partially, I do not get an error but I only get the advertisements from the Nuki Smart lock but no advertisements from Enocean devices.

If I use setFilterPolicy(3) I get the following error:
`E NimBLEScan: Error initiating GAP discovery procedure; rc=530, Invalid HCI Command Parameters`

(if I use setFilterPolicy(0) I get them all (and then some...) zo the sensors work)

Any ideas?

**Comment by h2zero** [comment]
I suspect the missing devices may be changing their address in which case the whitelist not work once the address changes.

**Comment by I-Connect** [comment]
I understand but would thsi be the cause of this error?

E NimBLEScan: Error initiating GAP discovery procedure; rc=530, Invalid HCI Command Parameters

**Comment by h2zero** [comment]
That I believe is caused by the controller. It's possible that the esp32 does not support that scan mode (3).
