### ISSUE TITLE
NimBLE & SerialBT Same TIme Crashing

### ISSUE THREAD

**Issue by Bwanna** [h2zero/NimBLE-Arduino#548]
**Setup:** ESP32 DevKit C

**Issue:** NimBLE & SerialBT crash when running same time.  (core ESP32 BLE & SerialBT run fine)
-I'm not yet experienced enough to decode the error msg and offer any suggestions.  Any Suggestions?

**Below is the Code and the Error Msg:
Sketch:**
`/*
 * NimBLE_Scan_Whitelist demo
 *
 * Created May 16, 2021
 * Author: h2zero
 */

#include <NimBLEDevice.h>
#include <NimBLEUtils.h>
#include <NimBLEScan.h>
#include <NimBLEAdvertisedDevice.h>

#include <BluetoothSerial.h>
BluetoothSerial SerialBT;

int scanTime = 5; //In seconds
NimBLEScan* pBLEScan;

void setup() {
  Serial.begin(115200);
  Serial.println("Scanning...");

  // Initialize Bluetooth Serial
  SerialBT.begin("ESP32");

  NimBLEDevice::init("");
  pBLEScan = NimBLEDevice::getScan();
  pBLEScan->setActiveScan(true);
  pBLEScan->setInterval(100);
  pBLEScan->setFilterPolicy(BLE_HCI_SCAN_FILT_NO_WL);
  pBLEScan->setWindow(99);
  pBLEScan-> setMaxResults (0);  //Results not stored, relies on Callback only to process data
}

void loop() {
  bleScannerLoop();
  bluetoothSerialLoop();
}

void bluetoothSerialLoop() {
  if (Serial.available()) {
    String termtext = Serial.readStringUntil('\n');
    int data = termtext.toInt();
    SerialBT.print(termtext);
    Serial.print(termtext);
  }
}
void bleScannerLoop() {
  BLEScanResults foundDevices = NimBLEDevice::getScan()->start(5);
  for (int i = 0; i < foundDevices.getCount(); i++) {
    NimBLEAdvertisedDevice device = foundDevices.getDevice(i);
    Serial.print("Found device: ");
    Serial.println(device.getAddress().toString().c_str());
  }
}
`
**Error Msg:**

`clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13924
ho 0 tail 12 room 4
load:0x40080400,len:3600
entry 0x400805f0
Scanning...
ESP_ERROR_CHECK failed: esp_err_t 0x103 (ESP_ERR_INVALID_STATE) at 0x400929dc
file: "d:\Arduinofiles\libraries\NimBLE-Arduino\src\NimBLEDevice.cpp" line 879
func: static void NimBLEDevice::init(const string&)
expression: esp_bt_controller_init(&bt_cfg)

abort() was called at PC 0x400929df on core 1

Backtrace: 0x4008395d:0x3ffcb0d0 0x400929e9:0x3ffcb0f0 0x40098925:0x3ffcb110 0x400929df:0x3ffcb190 0x400d37e2:0x3ffcb1b0 0x400d2237:0x3ffcb200 0x400e94af:0x3ffcb250

ELF file SHA256: eb7593b2f45f575b
`

**Comment by h2zero** [comment]
NimBLE is BLE only, classic Bluetooth cannot be used with this library.

**Comment by Bwanna** [comment]
> 
h2Zero,

Just to verify... the BluetoothSerial.h can't be used in the same sketch with the NimBLEDevice.h ?

Thanks,

**Comment by h2zero** [comment]
That's correct.

**Comment by Bwanna** [comment]
Thank you for the information.

**Comment by SamObde** [comment]
Is this still the case?  I am needing classic BT just for scanning to gather names, no actual connections.  Just gap event reporting.  Any chance this could be made to work?  Thanks!

**Comment by h2zero** [comment]
Yes, this is still the case.
