### ISSUE TITLE
After installing NimBLE from the library manager I get an error package

### ISSUE THREAD

**Issue by ghost** [h2zero/NimBLE-Arduino#556]
`#include <NimBLE2902.h>`
`fatal error: NimBLE2902.h: No such file or directory`

**Comment by SlitheringMule** [comment]
I commented the line out and it works fine now

**Comment by SlitheringMule** [comment]
Doesn't work now

**Comment by h2zero** [comment]
What version did you install? That file was removed a very long time ago, please use a newer version.
