### ISSUE TITLE
ADXL362 Library

### ISSUE THREAD

**Issue by j45p41** [h2zero/NimBLE-Arduino#587]
HI,

I am using adel library - https://github.com/annem/ADXL362/tree/master.

When I test on Arduino Uno the reading are fine of simpleread example.

However when I test with this library the ratings are showing but they are fluctuating between many different values and there is no value for temperature (which is a good indicator of it working) . I have tried changing SPI modes, I notice there is a special mode NRFX_SPIM3_NRF52840_ANOMALY_198_WORKAROUND_ENABLED but this does not seem to resolve the issue.

any suggestions pls?

BTW: Thanks for rest of this very useful library.

**Comment by h2zero** [comment]
Sorry, I do not know why this would be occuring and do not believe it to be related to this repo. There may be something to do with the Arduino core but I do not have the ability to reproduce at this time.

**Comment by j45p41** [comment]
Hi Thank you for your reply.

I actually managed to get it to work for wake-up, which what I needed. Still get it to read the temperature. I had to set chip select in the Adxl library.

**Comment by j45p41** [comment]
Just a quick update. I can confirm that temperature is also working after the breadboard was updated to PCB. Could have been a noise issue with breadboard wiring.
