### ISSUE TITLE
Newest version changes from 1.4.1 are not in platform.io

### ISSUE THREAD

**Issue by Kurisu-Null** [h2zero/NimBLE-Arduino#589]
Hey,

first of all thanks for the awesome lib!
I encountered the issue with the assert(notify rc == 0) crash and saw that there should be a fix for that in the code. But when I have the lib as a dependency in my platform.io project the bugfix is somehow not there.

could you please double check the version in platform.io?
Thanks!

**Comment by h2zero** [comment]
Can you share your pio env? Can you share the backtrace?

**Comment by h2zero** [comment]
Closing as stale.
