### ISSUE TITLE
Came across a broken link in the docs

### ISSUE THREAD

**Issue by JustTryingToGetSomeWorkDone** [h2zero/NimBLE-Arduino#598]
I was attempting to help out people with no comments on their issues and found the "See also" link on https://h2zero.github.io/esp-nimble-cpp/class_nim_b_l_e2904.html#details is broken. Somehow I'm super not surprised that bluetooth.com has missing documentation. Lol. Bluetooth is such a train-wreak.

Also found on line 17 in: https://github.com/h2zero/NimBLE-Arduino/blob/release/1.4/src/NimBLE2904.cpp

**Comment by h2zero** [comment]
Thanks, yes they have removed all the old xml files from the website.

**Comment by h2zero** [comment]
Fixed in [5b2d72a](https://github.com/h2zero/NimBLE-Arduino/commit/5b2d72a424af151929777afe058bc8329cb442c8)
