### ISSUE TITLE
How does bonding work?

### ISSUE THREAD

**Issue by shooshx** [h2zero/NimBLE-Arduino#602]
Bonding seem to be undocumented at all.

I'd like to be able to pair a device (a remote control) with my ESP32 and then have this device be able to just work after a reboot without having to trigger the advertise on the remote.
When does the bonding data saved? How can it be used to replace the scanning functionality?

**Comment by h2zero** [comment]
Bonding is for saving the credentials so that the pin etc does not need to be entered again. There is no way to avoid advertising as the stack would not be listening for connections otherwise.

**Comment by shooshx** [comment]
Thank you
