### ISSUE TITLE
Unable to Send Messages to ESP32 using "BLE_Write" or "Server"

### ISSUE THREAD

**Issue by AlEnterni** [h2zero/NimBLE-Arduino#607]
Hello

 I am currently facing an issue with my ESP32 development board and I'm seeking assistance to resolve it.

I have been trying to use the "BLE_Write" and "Server" examples for my ESP32, but unfortunately, I am unable to successfully send messages to the ESP32. Strangely, I can read messages without any issues, but the writing functionality seems to be problematic. I use mobile apps like nRF Connect or BLE Scanner.
I have followed the examples and documentation carefully, but I haven't been able to figure out what's causing the problem. I would greatly appreciate it if someone could provide guidance on how to troubleshoot and fix this issue.

Thank you in advance for your assistance. I'm looking forward to resolving this issue and continuing my ESP32 development journey.

Best regards,

**Comment by h2zero** [comment]
@AlEnterni Could you provide some example code to reproduce this, or better yet, some logging with debug logs enabled?

**Comment by h2zero** [comment]
This may have been a case of needing to write with or without response depending on the situation. Closing this now as there has been no response from the author.
