### ISSUE TITLE
Multi-connect support: start advertising && WiFi

### ISSUE THREAD

**Issue by fbritop** [h2zero/NimBLE-Arduino#608]
Is there any restrictions that NimBLE wont advertise if there is no internet connection?

I try con connect to an ESP32, with no problem where Wifi connection is OK, but if it disconnects, then I cannot connect to the device.

After the wifi connects, it outputs a message; Multi-connect support: start advertising

Thanks
Felipe Brito

**Comment by h2zero** [comment]
There is no internet connection required. Please post a debug log to diagnose
