### ISSUE TITLE
Stack canary watchpoint triggered (ipc0) when constantly notifying.

### ISSUE THREAD

**Issue by JoshPlayer1** [h2zero/NimBLE-Arduino#619]
Apologies as I don't code often. I have a project where I'm sending a lot of notifications at around 60-500 notifications per second with an ESP32-S3.

After about 2 minutes of notifying I get this error:
`Guru Meditation Error: Core  0 panic'ed (Unhandled debug exception). 
Debug exception reason: Stack canary watchpoint triggered (ipc0)`

the only difference in code on whether my program crashes is the inclusion of the following two lines in the main loop() function:
`pChar->setValue(Data);
 pChar->notify(true);`

Could I get insight as to why this error is happening and if I should be structuring my code differently so I don't use so much stack memory?

**Comment by JoshPlayer1** [comment]
After reading some more such as the usage tips in the docs folder and adding a vTaskDelay as a work around for the `assert failed: static int NimBLECharacteristic::handleGapEvent(uint16_t, uint16_t, ble_gatt_access_ctxt*, void*) NimBLECharacteristic.cpp:277 (rc == 0)`.

**Comment by h2zero** [comment]
You are sending notifications faster than BLE is designed to do. 100 per second or less would be most managable.
