### ISSUE TITLE
ESP32-S3 BLE Server Vs. Detection on PC Bluetooth Dongle

### ISSUE THREAD

**Issue by wamk9** [h2zero/NimBLE-Arduino#627]
Hi!

I need to create a project with bluetooth connection on my PC, but ANY BT library I use show only on my smartphone the connection.

My question:

Is this a caracteristic of ESP32-S3 BLE? Or I need do a extra config to work on my PC in NimBLE?

My dongle is a Baseus BT 5.0, like this:
https://pt.aliexpress.com/item/1005003601253541.html

Another thing, i try to use all examples but... Well, don't works on this situation...

**Comment by h2zero** [comment]
I'm not sure what you mean, does the PC not see the advertisements from the ESP32?

**Comment by wamk9** [comment]
> I'm not sure what you mean, does the PC not see the advertisements from the ESP32?

Yes, now i have success with this, but after 2 seconds or less my device disconnect on PC. See Code above:

`#include <NimBLEDevice.h>

#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"

static NimBLEServer* pServer;
static NimBLEService* pService;
static NimBLECharacteristic* pCharacteristic;

/**  None of these are required as they will be handled by the library with defaults. **
 **                       Remove as you see fit for your needs                        */
class ServerCallbacks: public NimBLEServerCallbacks {
    void onConnect(NimBLEServer* pServer) {
        Serial.println("Client connected");
        Serial.println("Multi-connect support: start advertising");
        NimBLEDevice::startAdvertising();
    };
    /** Alternative onConnect() method to extract details of the connection.
     *  See: src/ble_gap.h for the details of the ble_gap_conn_desc struct.
     */
    void onConnect(NimBLEServer* pServer, ble_gap_conn_desc* desc) {
        Serial.print("Client address: ");
        Serial.println(NimBLEAddress(desc->peer_ota_addr).toString().c_str());
        /** We can use the connection handle here to ask for different connection parameters.
         *  Args: connection handle, min connection interval, max connection interval
         *  latency, supervision timeout.
         *  Units; Min/Max Intervals: 1.25 millisecond increments.
         *  Latency: number of intervals allowed to skip.
         *  Timeout: 10 millisecond increments, try for 5x interval time for best results.
         */
         NimBLEDevice::startAdvertising();
        pServer->updateConnParams(desc->conn_handle, 24, 48, 0, 60);
    };
    void onDisconnect(NimBLEServer* pServer) {
        Serial.println("Client disconnected - start advertising");
        NimBLEDevice::startAdvertising();
    };
    void onMTUChange(uint16_t MTU, ble_gap_conn_desc* desc) {
        Serial.printf("MTU updated: %u for connection ID: %u\n", MTU, desc->conn_handle);
    };

/********************* Security handled here **********************
****** Note: these are the same return values as defaults ********/
    uint32_t onPassKeyRequest(){
        Serial.println("Server Passkey Request");
        /** This should return a random 6 digit number for security
         *  or make your own static passkey as done here.
         */
        return 123456;
    };

    bool onConfirmPIN(uint32_t pass_key){
        Serial.print("The passkey YES/NO number: ");Serial.println(pass_key);
        /** Return false if passkeys don't match. */
        return true;
    };

    void onAuthenticationComplete(ble_gap_conn_desc* desc){
        /** Check that encryption was successful, if not we disconnect the client */
        // if(!desc->sec_state.encrypted) {
        //     NimBLEDevice::getServer()->disconnect(desc->conn_handle);
        //     Serial.println("Encrypt connection failed - disconnecting client");
        //     return;
        // }
        Serial.println("Starting BLE work!");
    };
};

/** Handler class for characteristic actions */
class CharacteristicCallbacks: public NimBLECharacteristicCallbacks {
    void onRead(NimBLECharacteristic* pCharacteristic){
        Serial.print(pCharacteristic->getUUID().toString().c_str());
        Serial.print(": onRead(), value: ");
        Serial.println(pCharacteristic->getValue().c_str());
    };

    void onWrite(NimBLECharacteristic* pCharacteristic) {
        Serial.print(pCharacteristic->getUUID().toString().c_str());
        Serial.print(": onWrite(), value: ");
        Serial.println(pCharacteristic->getValue().c_str());
    };
    /** Called before notification or indication is sent,
     *  the value can be changed here before sending if desired.
     */
    void onNotify(NimBLECharacteristic* pCharacteristic) {
        Serial.println("Sending notification to clients");
    };


    /** The status returned in status is defined in NimBLECharacteristic.h.
     *  The value returned in code is the NimBLE host return code.
     */
    void onStatus(NimBLECharacteristic* pCharacteristic, Status status, int code) {
        String str = ("Notification/Indication status code: ");
        str += status;
        str += ", return code: ";
        str += code;
        str += ", ";
        str += NimBLEUtils::returnCodeToString(code);
        Serial.println(str);
    };

    void onSubscribe(NimBLECharacteristic* pCharacteristic, ble_gap_conn_desc* desc, uint16_t subValue) {
        String str = "Client ID: ";
        str += desc->conn_handle;
        str += " Address: ";
        str += std::string(NimBLEAddress(desc->peer_ota_addr)).c_str();
        if(subValue == 0) {
            str += " Unsubscribed to ";
        }else if(subValue == 1) {
            str += " Subscribed to notfications for ";
        } else if(subValue == 2) {
            str += " Subscribed to indications for ";
        } else if(subValue == 3) {
            str += " Subscribed to notifications and indications for ";
        }
        str += std::string(pCharacteristic->getUUID()).c_str();

        Serial.println(str);
    };
};

/** Handler class for descriptor actions */
class DescriptorCallbacks : public NimBLEDescriptorCallbacks {
    void onWrite(NimBLEDescriptor* pDescriptor) {
        std::string dscVal = pDescriptor->getValue();
        Serial.print("Descriptor witten value:");
        Serial.println(dscVal.c_str());
    };

    void onRead(NimBLEDescriptor* pDescriptor) {
        Serial.print(pDescriptor->getUUID().toString().c_str());
        Serial.println(" Descriptor read");
    };
};

/** Define callback instances globally to use for multiple Charateristics \ Descriptors */
static DescriptorCallbacks dscCallbacks;
static CharacteristicCallbacks chrCallbacks;

void setup() {
    Serial.begin(115200);
    Serial.println("Starting NimBLE Server");

    /** sets device name */
    NimBLEDevice::init("NimBLE-Arduino");

    pServer = NimBLEDevice::createServer();
    pServer->setCallbacks(new ServerCallbacks());

    pService = pServer->createService(SERVICE_UUID);
    pCharacteristic = pService->createCharacteristic(
                                               CHARACTERISTIC_UUID,
                                              NIMBLE_PROPERTY::READ |
                                              NIMBLE_PROPERTY::WRITE);

    pService->start();

    pCharacteristic->setValue("Test");
    pCharacteristic->setCallbacks(&chrCallbacks);

    NimBLEAdvertising* pAdvertising = NimBLEDevice::getAdvertising();
    //pAdvertising->addServiceUUID(pService->getUUID());
    pAdvertising->addServiceUUID(SERVICE_UUID);
    // pAdvertising->addServiceUUID(pBaadService->getUUID());
    /** If your device is battery powered you may consider setting scan response
     *  to false as it will extend battery life at the expense of less data sent.
     */
    //pAdvertising->setScanResponse(false);
    pAdvertising->start();

    Serial.println("Advertising Started");
}


void loop() {
  /** Do your thing here, this just spams notifications to all connected clients */
    //  if(pServer->getConnectedCount()) {
    // //     // NimBLEService* pSvc = pServer->getServiceByUUID("BAAD");
    // //     // if(pSvc) {
    // //     //     NimBLECharacteristic* pChr = pSvc->getCharacteristic("F00D");
    // //     //     if(pChr) {
    // //     //         pChr->notify(true);
    // //     //     }
    // //     // }
    // }
    //pServer->getConnectedCount();
    //pCharacteristic->setValue("Test loop");
    //pCharacteristic->notify();


  delay(100);
}`

I try remove notify to see if i have any diference reaction, but nothing happens...

**Comment by wamk9** [comment]
Any suggestion @h2zero?

**Comment by h2zero** [comment]
I would need to see the logs from the esp32 at debug level to provide much insight with this.

**Comment by dimityrivanov** [comment]
@h2zero how can I enable logs ?

**Comment by h2zero** [comment]
I believe this to be related to bluetooth classic, not this repo. please reopen if still having this issue.
