### ISSUE TITLE
NimBLEscan turn a wrong MAC adress by 2 in the last octet

### ISSUE THREAD

**Issue by kbaggen** [h2zero/NimBLE-Arduino#628]
Hi,
I ran into an issue where when I scan by my ESP32 DevKit the MAC-id is shown wrongly, e.g. it seems the BLEscan adds +2 to the last octet.

The issue seems to be reported at this link --> https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/misc_system_api.html#mac-address

The code for this area:

```
BLEScanResults foundDevices = pBLEScan->start(SCAN_TIME);
  deviceCount = foundDevices.getCount();
  Serial.print(deviceCount);
  Serial.println(F(" Devices Found."));
  pBLEScan->stop();
  BLEDevice::deinit(0);

  for (uint32_t i = 0; i < deviceCount; i++)
  {
    BLEAdvertisedDevice Device = foundDevices.getDevice(i);
    String DevString, DevData, DevRapt;
    DevString = Device.toString().c_str();
    DevData = DevString.substring(63);
MAC_data = Device.getAddress().toString().c_str(); 
    Serial.println(MAC_data);
}
```

Returns --> 78:e3:6d:3d:11:7e
Where the correct should be --> 78:e3:6d:3d:11:7**c** 

I am in doubt what to do to get over this?
I tried both NimBLEDevice.h and BLEDevice.h, and both seems to do the same error by 2 chippers!

Klaus

**Comment by h2zero** [comment]
The MAC address you are receiving is the correct BLE address. The MAC it seems you are looking to get is the esp32 base MAC, which the BLE stack will have no knowledge of.

**Comment by kbaggen** [comment]
ok, I solved by just disregards the last ciffer, hence, I close it :-)
