### ISSUE TITLE
How to require a passkey for Notify?

### ISSUE THREAD

**Issue by trullock** [h2zero/NimBLE-Arduino#630]
I have a server which sends out notifications.

I want only trusted clients to be able to connect (mac unknown) so wish to protect the connection with a passkey/pin.

I can't get nrfConnect to ask for a passkey without adding READ_ENC to my characteristic.

Does adding READ_ENC imply that clients can Read?

Am I misunderstanding the API, is this a missing feature, or am I not understanding the BT standard. Must you be able to read in order to notify?

Thanks

**Comment by h2zero** [comment]
To require all connections to be secure you can call `NimBLEDevice::startSecurity` in the onConnect callback.
Something like this : https://github.com/h2zero/NimBLE-Arduino/issues/92#issuecomment-720788573

**Comment by trullock** [comment]
Great, thanks for your help
