### ISSUE TITLE
ESP32-S3 compatable?

### ISSUE THREAD

**Issue by mike-rankin** [h2zero/NimBLE-Arduino#632]
Great library and I'm wondering if it is compatable with the ESP32-S3 hardware?
I am using the sketch here: https://www.youtube.com/watch?v=ExFxuvfCbAU&t=445s and it works with the ESP32 TTGO board that uses ble 4.2. It does not work on the newer ESP32-S3 hardware that has ble 5.0 but the library could be fine and be an issue on the wiresless ble Xiaomi modules. Not sure and I'm new to ble.
Thanks again!

**Comment by h2zero** [comment]
Hello, yes this library is compatible with the s3.
