### ISSUE TITLE
ESP32C3 don't advertise

### ISSUE THREAD

**Issue by dimityrivanov** [h2zero/NimBLE-Arduino#633]
Hello I saw that this library is supporting the chip but when I setup to be HID joystick for some reason its not visible and the same code works on esp32 dev kit with your library is there a way to enable debug or something so I can get more data ?

**Comment by h2zero** [comment]
@dimityrivanov did you figure out your issue?

**Comment by h2zero** [comment]
Closing this as there has been no response, please reopen if still an issue.
