### ISSUE TITLE
Is it possible to scan and detect smartphones?

### ISSUE THREAD

**Issue by Tirititelu** [h2zero/NimBLE-Arduino#639]
Hello everyone,

I have been testing (a lot) and reading a lot about BLE scanning and I am unable to detect any smartphone, with BLEScan or NimBLEScan sketches. At some points I have come to think that this is not possible, since from what I have read client devices, like smartphones, do not emit almost never to save power, but at least it should detect them when BLE is activated on them, as happens with any laptop, which does detect smartphones when you activate BLE. 

I have gone through all the posts on this forum and Neil Kolban's post and have not found the solution. I have been playing with the setPower() function, without success, it does not detect any smartphone.

So my question is simple, is it possible to detect them somehow with the ESP32 or is there any reason why it does not detect them. As I said at the beginning, if my laptop detects smartphones, I understand that ESP32 should too, but surely I'm missing something.

Thank you very much in advance.

Regards

**Comment by h2zero** [comment]
Have a look at the ESPresence repo, I think they do that there.
