### ISSUE TITLE
ble does not work when cpu set to 40mhz or bellow

### ISSUE THREAD

**Issue by Gibbz** [h2zero/NimBLE-Arduino#657]
I'm trying to optimize power on my esp32. So I have dropped the cpu speed to 40., but nimbleble stops working. The device does not show in the scanner at 40mhz or bellow.
Should this still work at 40mhz? Id ideally love to drop down to 10mhz.

Thanks

**Comment by toaster-robotics** [comment]
@Gibbz I think this is a esp32 thing. This is a screenshot of the Arduino IDE showing that WiFi (likely including BLE) drops out after 80MHz.
![screenshot](https://github.com/h2zero/NimBLE-Arduino/assets/141705577/cf33ebd6-6fbd-465b-a922-2d7db8f7a878)

**Comment by h2zero** [comment]
Hello, as stated above 80mhz is the minimum required for BLE/WiFi.
