### ISSUE TITLE
Is it possible to advertise the device name as a client?

### ISSUE THREAD

**Issue by sepp89117** [h2zero/NimBLE-Arduino#659]
Hi,
I'm trying to make the device name readable with an ESP32 BLE client with UUID 0x2a00.
The BLE server (GoPro camera) tries to read the device name (0x2a00) after pairing.
The client (ESP32 with NimBLE) sends back an error response 'attribute not found'.
I tried adding the following code in the setup, but the response to the GoPro's request remains 'Attribute not found':
```cpp
NimBLEAdvertising *pAdvertising = NimBLEDevice::getAdvertising();
pAdvertising->setName(DEVICE_NAME);
pAdvertising->start();
```

Log output:
```
D NimBLEAdvertising: >> Advertising start: customAdvData: 0, customScanResponseData: 0
D NimBLEAdvertising: << Advertising start
```

Wireshark recording excerpt:
![grafik](https://github.com/h2zero/NimBLE-Arduino/assets/43417395/c7c853bf-e9bf-415d-8e50-08a339cbb987)

Is there a way to do this with ESP32 and NimBLE? When pairing with a smartphone, the GoPro can read the device name of the smartphone.

Thanks a lot!

**Comment by h2zero** [comment]
You can do this by creating a server instance, do this before creating any clients:
```
NimBLEDevice::init("devicename");
NimBLEServer * pServer = NimBLEDevice::createServer();
pServer->start();
```

**Comment by sepp89117** [comment]
Thank you! I actually should have figured that out myself, sorry!
After including "NimBLEServer.h" your code worked.

Thanks again!
