### ISSUE TITLE
Question: meaning advertisedDevice::getAddressType()

### ISSUE THREAD

**Issue by Jeroen88** [h2zero/NimBLE-Arduino#67]
Not an issue but a question: how should I interpret the value returned by `getAddressType()`? I found [this](https://devzone.nordicsemi.com/f/nordic-q-a/27012/how-to-distinguish-between-random-and-public-gap-addresses) post. That post explains that the address type is coded into bits, but I am not sure if this is indeed the value the function returns. If so then the return value is as follows:
- Public device address: 0
- Static device address: 111, so 7
- Non-resolvable device address: 001, so 1
- Resolvable device address: 101, so 5

Is this actually the value returned?

**Comment by h2zero** [comment]
From ble.h:
```
#define BLE_ADDR_PUBLIC      (0x00)
#define BLE_ADDR_RANDOM      (0x01)
#define BLE_ADDR_PUBLIC_ID   (0x02)
#define BLE_ADDR_RANDOM_ID   (0x03)
```
Mainly you will only see the first 2.

**Comment by Jeroen88** [comment]
Thnx @h2zero!
