### ISSUE TITLE
API change - feature test macro missing

### ISSUE THREAD

**Issue by mhaberler** [h2zero/NimBLE-Arduino#673]
Hi,

switching espressif32 versions and matching NimBLE-Arduino or esp-nimble-cpp versions leads to contraptions like this:

`````
#ifdef NIMBLE_OLDAPI
    pBLEScan->setAdvertisedDeviceCallbacks(new scanCallbacks());
#else
    pBLEScan->setScanCallbacks(new scanCallbacks());
#endif
`````
did I overlook a feature test macro for the API change?
if not - could I suggest to add one?

thanks
Michael

**Comment by h2zero** [comment]
@mhaberler, if you use the NimBLE-Arduino Master branch instead of release/1.4 then the functions are the same and this conditional will not be necessary.

**Comment by mhaberler** [comment]
appreciated - thanks!
