### ISSUE TITLE
Error in converting EddystoneTLM negative temperatures to float

### ISSUE THREAD

**Issue by giovanni-foorban** [h2zero/NimBLE-Arduino#675]
In [NimBLEEddystoneTLM.cpp](https://github.com/h2zero/NimBLE-Arduino/blob/nimble-1.5.0/src/NimBLEEddystoneTLM.cpp) there is an issue when receiving negative numbers for temperature readings and when setting temperature.

For example: -0,1C is converted to approximately 256C.

On our side we fixed the issue like this:
```diff
/**
 * @brief Set the temperature to advertise.
 * @param [in] temp The temperature value.
 */
void NimBLEEddystoneTLM::setTemp(float temp) {
-  m_eddystoneData.temp = (uint16_t)temp;
+  m_eddystoneData.temp = ENDIAN_CHANGE_U16((int16_t)(temp * 256.0f)) ;
} // setTemp
/**
 * @brief Get the temperature being advertised.
 * @return The temperature value.
 */
float NimBLEEddystoneTLM::getTemp() {
-    return ENDIAN_CHANGE_U16(m_eddystoneData.temp) / 256.0f;
+ return (int16_t)ENDIAN_CHANGE_U16(m_eddystoneData.temp) / 256.0f;
} // getTemp
```

**Comment by h2zero** [comment]
Thanks! would you mind making a PR for this?

**Comment by Max93** [comment]
Hello @h2zero 

I am a colleague of Giovanni (@giovanni-foorban), who opened this issue. I have created a pull request to address the problem with negative temperature readings #677.

You can find the pull request here.

Thank you for your attention.

**Comment by Max93** [comment]
Hi @h2zero, when are you planning the next release ? Was it right to open the pr to release 1.4 ?

**Comment by h2zero** [comment]
I'll look to make a new release soon, hard to say when exactly
