### ISSUE TITLE
How to pass correct hid device name

### ISSUE THREAD

**Issue by DrSimgear** [h2zero/NimBLE-Arduino#703]
![image](https://github.com/user-attachments/assets/f13ba348-8185-4889-af2f-440711332288)
Device does not show up with the ble name given instead windows generates a name.

**Comment by ernest-cpu** [comment]
https://www.bluetooth.com/specifications/specs/human-interface-device-profile-1-1-1/    
5.3.3 SDP Attribute Summary: Service Name

**Comment by ernest-cpu** [comment]
https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/35

**Comment by h2zero** [comment]
> I read somewhere else that Windows takes the controller name from that attribute in the advertisment.
How to set that? No idea.

I'm not sure how windows recognizes the device name and as far as HID support is concerned I don't know much about it, the code for it is community supplied. 

There are 2 ways to set the name via BLE:
```NimBLEDevice::init("your device name")```
or:
```NimBLEAdvertising::setName("your device name")``` or ```NimBLEAdvertisementData::setName("your device name")``` if using custom data etc...

> To my opinion, we need better API documentation.

While this is true for any repo it's not easy to maintain and I welcome with open arms any contributions. I'm not sure what documentation is missing for this use case, can you elaborate?

Here is the way most of this HID stuff works, USB or Bluetooth, there is a VID and PID value, Windows probably looks at those first, compares to the table of registered devices and derives the name from the registry, ignoring any other data from the BLE device, this is only my guess. If I am correct in my suspicion, and windows ignores the values I have described how to set above, then there is nothing you can do unless you want to spend $$$$ to register your VID/PID to have it recognized by windows.

**Comment by h2zero** [comment]
Thanks, that makes sense. I don't know much about the HID stuff, never had to work with it.

I'd suggest looking at how all the other attributes are added and see if you can add this one and the same manner.

**Comment by h2zero** [comment]
Thanks for the update, confirms my suspicions that windows gets the name from the Bluetooth registry using the VID/PID which isn't home gamer friendly obviously.

**Comment by Volanaro** [comment]
Im having the same Problem, dose this mean its not possible? or can someone make some sort of guide :3?

**Comment by h2zero** [comment]
@Volanaro The only way that we know of at this time is to manually change the name in the Windows registry as there is no provision in the BLE HID spec to provide the product name.

**Comment by Volanaro** [comment]
ahh okay thanks!, wonding if it would be possible to spoof the bluetooth as usb... dout it.. that would be another problem initself lol

**Comment by h2zero** [comment]
Closing this as it is not an issue with this library.
