### ISSUE TITLE
esp_bt.h: No such file or directory

### ISSUE THREAD

**Issue by haimbilia** [h2zero/NimBLE-Arduino#704]
i keep having this issue when trying to compile with NimBLE library
i see this esp_bt.h file included in several places but couldn't find it in the library.

**Comment by haimbilia** [comment]
i tried fresh install on another computer and got the same error

**Comment by h2zero** [comment]
That file is included in the esp32-Arduino core, there is something wrong with your pio environment or board setting in Arduino IDE.

**Comment by haimbilia** [comment]
i also tried an older ide version and tried a different board. 
this is the code im trying to compile:
https://github.com/gromeck/BLE-Scanner

**Comment by h2zero** [comment]
Closing this as it is not an issue with this library.
