### ISSUE TITLE
NimBLEAddress initialization failure with 17bytes address string

### ISSUE THREAD

**Issue by homy-newfs8** [h2zero/NimBLE-Arduino#709]
Hi,

On ESP32-C3/S3 environment, crashed at below line with addr = `d3:0f:1c:70:7b:d2`.

https://github.com/h2zero/NimBLE-Arduino/blob/b6a169f1f2e939ce0ca11d003cc38ef141698d6a/src/NimBLEAddress.cpp#L57

May be `stoull()` should be used.

**Comment by h2zero** [comment]
Thanks, my unit test builds missed this as I forgot to build in 32 bit :(, will fix shortly.

**Comment by homy-newfs8** [comment]
Fix confirmed on current commit. Thanks!
