### ISSUE TITLE
Add client connect cancel

### ISSUE THREAD

**Issue by gkoh** [h2zero/NimBLE-Arduino#732]
I've found a need to allow a user to cancel an active client connection attempt.
For now, I've just direct called `ble_gap_conn_cancel()` which does the job and causes a `NimBLEClient::connect()` to abort.

It would be nice, but not necessary, to add something like `NimBLEClient::cancel()` or similar so abstractions are preserved.

**Comment by h2zero** [comment]
Hi @gkoh, that's a good idea and would be very easy to implement.
