### ISSUE TITLE
Maybe this PR is relevant for NimBLE too?

### ISSUE THREAD

**Issue by Jeroen88** [h2zero/NimBLE-Arduino#76]
@h2zero I saw [this](https://github.com/espressif/arduino-esp32/pull/4126) today. Maybe relevant for NimBLE too?

**Comment by h2zero** [comment]
@Jeroen88 Thanks, yes this was addressed here the other day in commit aaf42f8. Maybe that's where that PR got it's inspiration lol.

**Comment by Jeroen88** [comment]
LOL
