### ISSUE TITLE
Compilation Error when Roles Disabled

### ISSUE THREAD

**Issue by brskt-dev** [h2zero/NimBLE-Arduino#764]
I am following the documentation to disable some unused features in my context, but **the compilations fail when ROLE_CENTRAL is disabled**.

Error:
`Linking .pio\build\esp32dev\firmware.elf
c:/users/bruno/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\lib95d\libNimBLE-Arduino.a(ble_hs_resolv.c.o):(.literal.ble_hs_resolv_gen_priv_addr+0x4): undefined reference 
to ble_sm_alg_encrypt'
c:/users/bruno/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\lib95d\libNimBLE-Arduino.a(ble_hs_resolv.c.o): in function ble_hs_resolv_gen_priv_addr':
C:\Users\bruno\Documents\Embedded Repositories\Axia Badge Repos\Axia_Badge/.pio/libdeps/esp32dev/NimBLE-Arduino/src/nimble/nimble/host/src/ble_hs_resolv.c:408: undefined reference to ble_sm_alg_encrypt'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32dev\firmware.elf] Error 1`

Documentation I am using as reference: [NimBLE Config](https://h2zero.github.io/NimBLE-Arduino/md__command_line_config.html)

I am using the platformio environment and the following configuration in platformio.ini:
```c++
[env:esp32dev]
; Enviroment Configurations
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor Configurations
monitor_dtr = 0
monitor_rts = 0
monitor_speed = 115200
monitor_filters = time

; Build Configurations
board_build.f_cpu = 160000000L
board_build.upload_speed = 921600
board_build.filesystem = littlefs
board_build.partitions = partitions_schema.csv

; Upload Configurations
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

; Build Flags Configurations
build_flags =
	-D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED
	-D CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
	-D CONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED

; Library Dependencies Configurations
lib_ldf_mode = deep+
lib_deps = 
	h2zero/NimBLE-Arduino@^1.4.2
``` 

**I tested and removing the -D CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED definition resolves the error, however I would like to disable this functionality because in my use case the device only performs scans (OBSERVER_ROLE).**

**Comment by h2zero** [comment]
Fixed with release 1.4.3
