### ISSUE TITLE
Using ``NimBLERemoteCharacteristic::getValue()`` in callbacks for ``NimBLERemoteCharacteristic::subscribe()``

### ISSUE THREAD

**Issue by Laxilef** [h2zero/NimBLE-Arduino#778]
Hi,

I looked at PR #49 but couldn't figure out if I can use method ``NimBLERemoteCharacteristic::getValue()`` in callbacks?
The PR says that we should pass a ``timestamp`` to prevent re-reading, but is this relevant now?

Or can we just use such an expression now?
```C
pChar->subscribe(true, [](NimBLERemoteCharacteristic* pChar, uint8_t* pData, size_t length, bool isNotify) {
  // ...
  auto value = pChar->getValue<short>();
  // ...
});
```

**Comment by h2zero** [comment]
@Laxilef you can freely call this function, it just returns the internally stored value, does not trigger a read.

**Comment by Laxilef** [comment]
Awesome! Thanks
