### ISSUE TITLE
Won't compile when CONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED is defined

### ISSUE THREAD

**Issue by davidlao2k** [h2zero/NimBLE-Arduino#809]
Un-comment // #define CONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED in nimconfig.h to repro

--
/Users/davidlao/Arduino/libraries/NimBLE-Arduino/src/NimBLEClient.cpp:533:44: error: return type 'class NimBLEConnInfo' is incomplete
  533 | NimBLEConnInfo NimBLEClient::getConnInfo() const {
      |                                            ^~~~~

**Comment by davidlao2k** [comment]
Not sure if it makes a difference, it was with ESP32C3 compiler

**Comment by h2zero** [comment]
This has been fixed in #801 and a new release will be published soon.

**Comment by davidlao2k** [comment]
Thanks for the quick fix!
