### ISSUE TITLE
Why does scanEndedCB get called twice in client connection example?

### ISSUE THREAD

**Issue by elguiri** [h2zero/NimBLE-Arduino#81]
Hi

Firstly I would like to say thanks for the library; I got stuck very quickly using the "built in" library on an esp32 arduino project needing multi client connect, and then discovered this which has given me confidence to proceed.

I have a query relating to the NimBLE_Client.ino example...

When the preferred service is found by scanning, getScan()->stop() is called which triggers the scanEndedCB callback.

That callback is then unexpectedly triggered again after the client is connected (even though the scan has not been restarted at that point).

Is this behaviour by design?

Thanks

**Comment by h2zero** [comment]
Hi @elguiri, there were some recent changes in that code and they may have introduced this bug. I will look into this and get it fixed.

Thanks for reporting!

**Comment by h2zero** [comment]
I just made PR #82 to address this.

**Comment by elguiri** [comment]
Hi @h2zero

Thanks for the quick response!

I've tested with the revised code and the callback is no longer called twice.

Cheers

**Comment by h2zero** [comment]
Great, thanks for the feedback!
