### ISSUE TITLE
Replacement of getSubscribedCount() for 2.x

### ISSUE THREAD

**Issue by Abasz** [h2zero/NimBLE-Arduino#814]
I understand from the 2.x release notes that getSubscribedCount() method was removed.

But from the release notes its unclear how this functionality can be achived from the "host stack". 

_"Removed tracking of client characteristic subscription status from NimBLEServer and NimBLECharacteristic and instead uses
the functions and tracking in the host stack."_

My use case is that I don not call notify() on a characteristic in case there are no subscribers.

**Comment by h2zero** [comment]
You should handle this in your callback class but overriding the onSubscribe callback.

**Comment by Abasz** [comment]
While I understand you point for simplification of your code base, this change makes the consumers life much more difficult. 

I have 5 characteristics (I am not saying its a lot but still), but I would need to implement tracking for each which means the need to implement onSubscribe for all of them as well as implement the onDisconnect, and there do matching of the disconnected client Id. This basically means a full wrapper around connection handling.... 

This was already done in the previous version of the library which made life much simple. I have not checked how much bytes removing this saved or performance increase this brought, but purely from my perspective I would argue that it was worth it.

**Comment by h2zero** [comment]
The main reason it was removed is because it is unnecessary, you can call notify all you want and it won't do anything if there are no subscribers.

**Comment by Abasz** [comment]
Strictly from your library's perspective you are right. Just guarding the notify() on its own makes little sense. But this API provided guard against running any time consuming code or calculation and create the payload that would have been send via the notify. That is what I used for not just to guard the notify it self. So I would argue that it is unnecessary purely because notify does nothing if there are no subscribers.

**Comment by h2zero** [comment]
Okay, that makes more sense for sure. However, I didn't like the resource use being pushed on to every application, the vector alone was using 12+bytes per characteristic. When using this library on something like an nRF52 with a dozen characteristics it was using a 150+ bytes out of the less than 800 bytes left over for little to no use for many of those as it was applied to ones that don't have notification capability as well. 

These sorts of changes are always difficult to make. I believe that as long as a mechanism is in place for an application to do what it needs then the library should be minimized where possible and the application can expand on it if the right tools are included with the library.

>I have 5 characteristics (I am not saying its a lot but still), but I would need to implement tracking for each which means the need to implement onSubscribe for all of them as well as implement the onDisconnect, and there do matching of the disconnected client Id. This basically means a full wrapper around connection handling....

Let me address this for you:
```
class CharacteristicCallbacks : public NimBLECharacteristicCallbacks {
    void onSubscribe(NimBLECharacteristic* pCharacteristic, NimBLEConnInfo& connInfo, uint16_t subValue) override {
        if (subValue) {
            m_subCount++;
        } else if (m_subCount) {
            m_subCount--;
        }
    }
  public:
    uint8_t getSubscribedCount() { return m_subCount; }

  private:
    uint8_t m_subCount{0};
};

 /// elsewhere in code
    pCharacteristic->setCallbacks( new CharacteristicCallbacks());
    CharacteristicCallbacks* pCallbacks = (CharacteristicCallbacks*)pCharacteristic->getCallbacks();
    if (pCallbacks->getSubscribedCount()){}
```

Note that you do not need to implement anything for disconnect as the onSubscribe callback will be called with a subvalue of 0.

**Comment by Abasz** [comment]
>using a 150+ bytes out of the less than 800 bytes 

Exactly why I said from my perspective its not worth it :) (ESP32 with at least 4mb)

> Note that you do not need to implement anything for disconnect as the onSubscribe callback will be called with a subvalue of 0.

Now that is interesting, I was not aware of this! This in fact makes life much easier. I was thinking of the need for tracking the client IDs and then removing in the onDisconnect (exactly in a vector). With the subValue being called with 0 actually allows simplification in my code in other areas! Thanks for suggesting.

I will close this issue as I see that this decision is final from your side no point in dragging this further on :)

**Comment by h2zero** [comment]
> Exactly why I said from my perspective its not worth it :) (ESP32 with at least 4mb)

I was referring to ram but it's far mor impactful on other chips for sure.

>Now that is interesting, I was not aware of this! This in fact makes life much easier. I was thinking of the need for tracking the client IDs and then removing in the onDisconnect (exactly in a vector). With the subValue being called with 0 actually allows simplification in my code in other areas! Thanks for suggesting.

>I will close this issue as I see that this decision is final from your side no point in dragging this further on :)

It's a good discussion and I appreciate you bringing it up.
